In [1]:
from mesa.batchrunner import BatchRunner, BatchRunnerMP
import pandas as pd
import numpy as np
from model import Environment
from os import cpu_count

Market Size and Distribution Experiment

In [2]:
#Experiment 1 Variables 
fixed_params = {
  "N": 25,
  "cap_size": .35,
  "mSize":  .5,
  "lobby": .33,
  "dec": .005  
}
variable_params = {
    "am": [False, True]
}

In [3]:
experiment1 = BatchRunnerMP(Environment,
    nr_processes= None,
    variable_parameters = variable_params, 
    fixed_parameters = fixed_params,
    iterations = 10,
    max_steps = 200)

BatchRunner MP will use 16 processors.

In [4]:
experiment1.run_all()

20it [00:10,  1.93it/s]

(None,
 None,
 OrderedDict([((False, 25, 0.35, 0.5, 0.33, 0.005, 9),
                    mean_tech  total_lobby     n_allow   mean_prod   emissions  \
               0         4.44     0.000000  631.000000   71.913116  971.035036
               1         4.44   254.949229  628.606792   61.821870  411.000000
               2         4.92   475.786309  627.603013   55.484322  381.000000
               3         5.92   521.105783  626.586902   57.549445  341.000000
               4         6.40   718.879193  624.190950   67.479501  284.000000
               ..         ...          ...         ...         ...         ...
               195       9.48  2470.842774  373.073059  107.893188  306.000000
               196       9.48  2124.103767  372.073059  108.128779  360.000000
               197       9.48  2103.784149  371.708258  108.052556  342.000000
               198       9.48  2248.010367  370.708258  106.670633  406.000000
               199       9.48  2070.672944  370.493965  105.708624  248.000000

                        mean_cash  period
               0       719.131159       0
               1      1179.308715       1
               2      1567.090986       2
               3      1999.776387       3
               4      2502.216613       4
               ..             ...     ...
               195  156489.745662     195
               196  157339.282998     196
               197  158165.470460     197
               198  158963.498185     198
               199  159784.645594     199

               [200 rows x 7 columns]),
              ((False, 25, 0.35, 0.5, 0.33, 0.005, 0),
                    mean_tech  total_lobby     n_allow  mean_prod  emissions      mean_cash  \
               0         4.68     0.000000  480.000000  63.009901  739.74992     630.099005
               1         4.68   179.952386  478.000000  51.680715  314.00000    1024.481041
               2         5.20   366.094773  476.000000  53.371669  306.00000    1412.771951
               3         6.08   458.593097  475.717529  52.186378  281.00000    1811.302619
               4         6.60   502.288543  474.813349  57.622846  259.00000    2265.035213
               ..         ...          ...         ...        ...        ...            ...
               195       9.32  2081.707388  298.945994  88.409634  512.00000  130164.239396
               196       9.32  1863.200923  297.945994  85.534600  331.00000  130818.842797
               197       9.32  1812.186436  297.237992  90.240454  315.00000  131515.524489
               198       9.32  1738.318906  296.796902  88.803253  310.00000  132204.277048
               199       9.32  1769.876706  296.675578  88.707581  319.00000  132874.537329

                    period
               0         0
               1         1
               2         2
               3         3
               4         4
               ..      ...
               195     195
               196     196
               197     197
               198     198
               199     199

               [200 rows x 7 columns]),
              ((False, 25, 0.35, 0.5, 0.33, 0.005, 2),
                    mean_tech  total_lobby     n_allow   mean_prod    emissions  \
               0         3.88     0.000000  772.000000   76.895994  1188.763967
               1         3.88   294.437394  769.920221   68.578539   512.000000
               2         4.56   425.829420  767.206518   59.943924   567.000000
               3         5.52   697.989880  765.073540   69.463141   383.000000
               4         6.08   935.436748  763.122122   80.205916   445.000000
               ..         ...          ...         ...         ...          ...
               195       9.56  2954.241142  460.807533  118.931386   533.000000
               196       9.56  3556.696862  458.807533  121.363651   455.000000
               197       9.56  3242.329835  457.837341  118.527642   569.000000
               198       9.56  3193.380966  457.400335  117.820736   494.000000
               199       9.56  3497.022393  455.598164  118.070068   505.000000

                        mean_cash  period
               0       768.959938       0
               1      1277.553260       1
               2      1732.577818       2
               3      2225.636795       3
               4      2828.595430       4
               ..             ...     ...
               195  174493.083608     195
               196  175349.959153     196
               197  176230.763154     197
               198  177116.313603     198
               199  177955.077926     199

               [200 rows x 7 columns]),
              ((False, 25, 0.35, 0.5, 0.33, 0.005, 5),
                    mean_tech  total_lobby     n_allow   mean_prod   emissions  \
               0         3.44     0.000000  543.000000   76.989711  836.227095
               1         3.52   225.061289  541.000000   67.632727  427.000000
               2         4.20   362.902821  539.000000   66.923026  423.000000
               3         5.20   476.815002  537.255995   66.807536  340.000000
               4         5.96   573.806387  535.255995   67.802508  523.000000
               ..         ...          ...         ...         ...         ...
               195       9.84  1938.576246  331.597744   98.465188  323.000000
               196       9.84  1995.138146  330.852071   94.360819  434.000000
               197       9.84  2048.820921  330.337198  100.167864  409.000000
               198       9.84  2015.992826  329.951283  100.016924  276.000000
               199       9.84  1931.174767  328.951283   94.727524  422.000000

                        mean_cash  period
               0       769.897108       0
               1      1267.398660       1
               2      1781.524490       2
               3      2291.685323       3
               4      2795.495435       4
               ..             ...     ...
               195  166664.097605     195
               196  167354.174970     196
               197  168099.282281     197
               198  168853.931926     198
               199  169565.380200     199

               [200 rows x 7 columns]),
              ((False, 25, 0.35, 0.5, 0.33, 0.005, 3),
                    mean_tech  total_lobby     n_allow   mean_prod   emissions  \
               0         3.96     0.000000  492.000000   74.888550  757.663355
               1         3.96   189.371205  490.669991   60.349621  381.000000
               2         4.68   246.809774  489.871263   55.512479  324.000000
               3         5.60   280.160019  488.014239   53.852162  391.000000
               4         5.96   375.453033  486.014239   62.682686  316.000000
               ..         ...          ...         ...         ...         ...
               195       9.36  1090.970881  303.833203   98.235076  242.000000
               196       9.36  1008.665195  303.195604  100.961929  332.000000
               197       9.36   922.633308  302.902043   98.726845  322.000000
               198       9.36   926.464082  301.902043  104.573169  280.000000
               199       9.36  1075.453986  301.264950  102.445120  458.000000

                        mean_cash  period
               0       748.885497       0
               1      1190.512599       1
               2      1627.663829       2
               3      2042.206109       3
               4      2502.831312       4
               ..             ...     ...
               195  151210.244208     195
               196  152000.706831     196
               197  152770.841344     197
               198  153595.318286     198
               199  154341.994214     199

               [200 rows x 7 columns]),
              ((False, 25, 0.35, 0.5, 0.33, 0.005, 4),
                    mean_tech  total_lobby     n_allow  mean_prod   emissions      mean_cash  \
               0         3.92     0.000000  431.000000  81.566594  663.209839     815.665939
               1         4.00   140.381942  429.000000  57.256488  341.000000    1234.190823
               2         4.60   212.990676  427.000000  60.231868  298.000000    1691.029940
               3         5.56   278.290045  425.248843  60.944920  309.000000    2135.292879
               4         6.20   338.111926  423.896972  68.343835  190.000000    2647.846797
               ..         ...          ...         ...        ...         ...            ...
               195       9.44   690.806906  271.197030  91.687151  215.000000  145753.173138
               196       9.44   775.084737  270.197030  94.893582  368.000000  146464.943096
               197       9.44   682.388489  269.197030  88.263677  471.000000  147138.006587
               198       9.44   610.623366  268.522721  87.759357  244.000000  147803.911068
               199       9.44   580.195250  268.310848  95.966056  245.000000  148555.571290

                    period
               0         0
               1         1
               2         2
               3         3
               4         4
               ..      ...
               195     195
               196     196
               197     197
               198     198
               199     199

               [200 rows x 7 columns]),
              ((False, 25, 0.35, 0.5, 0.33, 0.005, 8),
                    mean_tech  total_lobby     n_allow  mean_prod   emissions      mean_cash  \
               0         3.52     0.000000  506.000000  71.005050  778.754014     710.050500
               1         3.60   141.157552  505.629574  50.114957  355.000000    1088.328487
               2         4.36   204.245258  503.854668  48.544598  354.000000    1456.171088
               3         5.28   277.939431  503.591639  52.094011  333.000000    1842.065031
               4         5.84   265.305006  501.963334  57.732999  306.000000    2318.078226
               ..         ...          ...         ...        ...         ...            ...
               195       9.32  1530.867294  313.589516  89.832323  270.000000  148346.534134
               196       9.32  1422.119220  312.589516  86.410668  350.000000  148979.525108
               197       9.32  1376.934895  311.816841  84.695250  520.000000  149590.372840
               198       9.32  1374.012924  311.146502  86.481891  232.000000  150211.770768
               199       9.32  1370.628003  310.762666  87.082497  229.000000  150852.294213

                    period
               0         0
               1         1
               2         2
               3         3
               4         4
               ..      ...
               195     195
               196     196
               197     197
               198     198
               199     199

               [200 rows x 7 columns]),
              ((False, 25, 0.35, 0.5, 0.33, 0.005, 6),
                    mean_tech  total_lobby     n_allow   mean_prod   emissions  \
               0         3.76     0.000000  580.000000   71.271330  893.477974
               1         3.84   221.588701  578.000000   58.014131  410.000000
               2         4.20   429.759973  576.332896   62.119840  424.000000
               3         5.16   485.013166  574.332896   58.913291  478.000000
               4         5.92   600.086083  572.612463   68.999357  270.000000
               ..         ...          ...         ...         ...         ...
               195       9.48  2645.988231  351.434346  113.037128  324.000000
               196       9.48  2871.866154  350.434346  111.229753  503.000000
               197       9.48  2442.319232  350.310267  109.827735  323.000000
               198       9.48  2210.973847  349.484147  104.699470  382.000000
               199       9.48  1819.203490  348.484147  101.561324  488.000000

                        mean_cash  period
               0       712.713298       0
               1      1139.518426       1
               2      1590.750471       2
               3      2034.124431       3
               4      2563.452861       4
               ..             ...     ...
               195  159630.452368     195
               196  160450.582525     196
               197  161309.306492     197
               198  162119.178889     198
               199  162927.123225     199

               [200 rows x 7 columns]),
              ((False, 25, 0.35, 0.5, 0.33, 0.005, 7),
                    mean_tech  total_lobby     n_allow   mean_prod   emissions  \
               0         3.84     0.000000  585.000000   79.870161  901.077488
               1         3.88   212.511531  583.356740   62.334208  473.000000
               2         4.64   307.709369  581.356740   55.305355  424.000000
               3         5.60   388.457454  579.572613   61.889869  412.000000
               4         6.12   505.800672  578.685155   77.995903  418.000000
               ..         ...          ...         ...         ...         ...
               195       9.76  2187.473105  350.986302  109.185817  308.000000
               196       9.76  2091.092357  350.228429  101.969952  396.000000
               197       9.76  2241.654389  349.367265  112.151089  315.000000
               198       9.76  2200.048146  348.367265  110.688034  438.000000
               199       9.76  2336.588896  348.180493  109.100946  399.000000

                        mean_cash  period
               0       798.701610       0
               1      1255.532667       1
               2      1667.813357       2
               3      2139.436691       3
               4      2749.611488       4
               ..             ...     ...
               195  167532.140728     195
               196  168292.178615     196
               197  169134.967766     197
               198  169975.274343     198
               199  170779.427146     199

               [200 rows x 7 columns]),
              ((False, 25, 0.35, 0.5, 0.33, 0.005, 1),
                    mean_tech  total_lobby     n_allow   mean_prod    emissions  \
               0         4.16     0.000000  663.000000   78.386738  1021.479124
               1         4.28   241.280951  662.128410   64.195962   469.000000
               2         4.76   442.948357  660.062929   65.922795   460.000000
               3         5.60   662.958006  657.472510   71.432777   409.000000
               4         6.24   691.159501  654.472510   73.144026   396.000000
               ..         ...          ...         ...         ...          ...
               195       9.72  2915.932287  383.231508  120.701658   403.000000
               196       9.72  2987.768924  382.793654  120.179541   446.000000
               197       9.72  3056.442162  381.880613  121.482367   261.000000
               198       9.72  2963.262658  381.581775  120.944779   523.000000
               199       9.72  3317.566665  380.755677  119.720565   348.000000

                        mean_cash  period
               0       783.867378       0
               1      1271.281737       1
               2      1763.184405       2
               3      2286.942788       3
               4      2863.997777       4
               ..             ...     ...
               195  172314.899998     195
               196  173216.351356     196
               197  174131.995351     197
               198  175057.881177     198
               199  175921.481628     199

               [200 rows x 7 columns]),
              ((True, 25, 0.35, 0.5, 0.33, 0.005, 3),
                    mean_tech  total_lobby     n_allow   mean_prod  emissions    mean_cash  \
               0         3.60     0.000000  484.000000   75.921340  745.28365   759.213399
               1         3.60   179.126325  482.000000   56.245304  378.00000   723.473620
               2         4.24   293.577764  480.000000   53.631643  477.00000   696.843090
               3         5.12   508.596989  479.768853   65.819373  383.00000   733.099104
               4         5.68   766.210346  479.504919   77.105576  448.00000   825.906501
               ..         ...          ...         ...         ...        ...          ...
               195       9.36  2023.373913  298.273906  100.466200  367.00000  1164.862183
               196       9.36  1902.903971  297.273906  100.572994  277.00000  1205.359113
               197       9.36  1977.837886  296.273906   99.134966  224.00000  1182.560069
               198       9.36  2071.425587  295.888519   99.032976  277.00000  1172.533929
               199       9.36  2080.223975  294.888519   96.816205  373.00000  1162.090290

                    period
               0         0
               1         1
               2         2
               3         3
               4         4
               ..      ...
               195     195
               196     196
               197     197
               198     198
               199     199

               [200 rows x 7 columns]),
              ((True, 25, 0.35, 0.5, 0.33, 0.005, 4),
                    mean_tech  total_lobby     n_allow  mean_prod   emissions    mean_cash  \
               0         4.84     0.000000  346.000000  88.454212  532.920909   884.542122
               1         4.88   103.024982  345.000000  58.192279  252.000000   842.936047
               2         5.36   172.304443  344.000000  56.357353  250.000000   786.363237
               3         6.16   269.320510  343.749136  69.677483  249.000000   866.340469
               4         6.68   359.067696  342.767232  73.874735  327.000000   908.054220
               ..         ...          ...         ...        ...         ...          ...
               195       9.72   257.280912  208.302609  72.394691  180.000000  1023.520475
               196       9.72   267.800205  208.017914  72.722260  193.000000  1009.889214
               197       9.72   341.581738  207.251779  89.662049  246.000000  1144.247081
               198       9.72   297.668211  207.097418  73.896250  221.000000  1112.938988
               199       9.72   257.830867  206.097418  68.744318  199.000000  1047.321766

                    period
               0         0
               1         1
               2         2
               3         3
               4         4
               ..      ...
               195     195
               196     196
               197     197
               198     198
               199     199

               [200 rows x 7 columns]),
              ((True, 25, 0.35, 0.5, 0.33, 0.005, 0),
                    mean_tech  total_lobby     n_allow  mean_prod   emissions    mean_cash  \
               0         4.56     0.000000  364.000000  84.571508  560.677633   845.715084
               1         4.68   132.244627  363.000000  64.038270  297.000000   863.286116
               2         5.12   223.218648  362.579478  54.202426  341.000000   769.324783
               3         5.84   310.124126  362.140140  63.400215  328.000000   808.001253
               4         6.32   445.124455  361.140140  75.155824  299.000000   897.805029
               ..         ...          ...         ...        ...         ...          ...
               195       9.60   762.139200  227.400370  67.294086  275.000000  1059.318635
               196       9.60   818.978338  226.961969  77.720361  185.000000  1049.492290
               197       9.60   856.601889  225.961969  83.594785  194.000000  1104.823564
               198       9.60   822.986589  225.712648  80.512668  209.000000  1108.049695
               199       9.60   680.412674  225.013749  86.963046  249.000000  1188.714886

                    period
               0         0
               1         1
               2         2
               3         3
               4         4
               ..      ...
               195     195
               196     196
               197     197
               198     198

In [5]:
od = experiment1.get_collector_model()

In [6]:
print(od)

OrderedDict([((False, 25, 0.35, 0.5, 0.33, 0.005, 9),      mean_tech  total_lobby     n_allow   mean_prod   emissions  \
0         4.44     0.000000  631.000000   71.913116  971.035036
1         4.44   254.949229  628.606792   61.821870  411.000000
2         4.92   475.786309  627.603013   55.484322  381.000000
3         5.92   521.105783  626.586902   57.549445  341.000000
4         6.40   718.879193  624.190950   67.479501  284.000000
..         ...          ...         ...         ...         ...
195       9.48  2470.842774  373.073059  107.893188  306.000000
196       9.48  2124.103767  372.073059  108.128779  360.000000
197       9.48  2103.784149  371.708258  108.052556  342.000000
198       9.48  2248.010367  370.708258  106.670633  406.000000
199       9.48  2070.672944  370.493965  105.708624  248.000000

         mean_cash  period
0       719.131159       0
1      1179.308715       1
2      1567.090986       2
3      1999.776387       3
4      2502.216613       4
..             ...     ...
195  156489.745662     195
196  157339.282998     196
197  158165.470460     197
198  158963.498185     198
199  159784.645594     199

[200 rows x 7 columns]), ((False, 25, 0.35, 0.5, 0.33, 0.005, 0),      mean_tech  total_lobby     n_allow  mean_prod  emissions      mean_cash  \
0         4.68     0.000000  480.000000  63.009901  739.74992     630.099005
1         4.68   179.952386  478.000000  51.680715  314.00000    1024.481041
2         5.20   366.094773  476.000000  53.371669  306.00000    1412.771951
3         6.08   458.593097  475.717529  52.186378  281.00000    1811.302619
4         6.60   502.288543  474.813349  57.622846  259.00000    2265.035213
..         ...          ...         ...        ...        ...            ...
195       9.32  2081.707388  298.945994  88.409634  512.00000  130164.239396
196       9.32  1863.200923  297.945994  85.534600  331.00000  130818.842797
197       9.32  1812.186436  297.237992  90.240454  315.00000  131515.524489
198       9.32  1738.318906  296.796902  88.803253  310.00000  132204.277048
199       9.32  1769.876706  296.675578  88.707581  319.00000  132874.537329

     period
0         0
1         1
2         2
3         3
4         4
..      ...
195     195
196     196
197     197
198     198
199     199

[200 rows x 7 columns]), ((False, 25, 0.35, 0.5, 0.33, 0.005, 2),      mean_tech  total_lobby     n_allow   mean_prod    emissions  \
0         3.88     0.000000  772.000000   76.895994  1188.763967
1         3.88   294.437394  769.920221   68.578539   512.000000
2         4.56   425.829420  767.206518   59.943924   567.000000
3         5.52   697.989880  765.073540   69.463141   383.000000
4         6.08   935.436748  763.122122   80.205916   445.000000
..         ...          ...         ...         ...          ...
195       9.56  2954.241142  460.807533  118.931386   533.000000
196       9.56  3556.696862  458.807533  121.363651   455.000000
197       9.56  3242.329835  457.837341  118.527642   569.000000
198       9.56  3193.380966  457.400335  117.820736   494.000000
199       9.56  3497.022393  455.598164  118.070068   505.000000

         mean_cash  period
0       768.959938       0
1      1277.553260       1
2      1732.577818       2
3      2225.636795       3
4      2828.595430       4
..             ...     ...
195  174493.083608     195
196  175349.959153     196
197  176230.763154     197
198  177116.313603     198
199  177955.077926     199

[200 rows x 7 columns]), ((False, 25, 0.35, 0.5, 0.33, 0.005, 5),      mean_tech  total_lobby     n_allow   mean_prod   emissions  \
0         3.44     0.000000  543.000000   76.989711  836.227095
1         3.52   225.061289  541.000000   67.632727  427.000000
2         4.20   362.902821  539.000000   66.923026  423.000000
3         5.20   476.815002  537.255995   66.807536  340.000000
4         5.96   573.806387  535.255995   67.802508  523.000000
..         ...          ...         ...         ...         ...
195       9.84  1938.576246  331.597744   98.465188  323.000000
196       9.84  1995.138146  330.852071   94.360819  434.000000
197       9.84  2048.820921  330.337198  100.167864  409.000000
198       9.84  2015.992826  329.951283  100.016924  276.000000
199       9.84  1931.174767  328.951283   94.727524  422.000000

         mean_cash  period
0       769.897108       0
1      1267.398660       1
2      1781.524490       2
3      2291.685323       3
4      2795.495435       4
..             ...     ...
195  166664.097605     195
196  167354.174970     196
197  168099.282281     197
198  168853.931926     198
199  169565.380200     199

[200 rows x 7 columns]), ((False, 25, 0.35, 0.5, 0.33, 0.005, 3),      mean_tech  total_lobby     n_allow   mean_prod   emissions  \
0         3.96     0.000000  492.000000   74.888550  757.663355
1         3.96   189.371205  490.669991   60.349621  381.000000
2         4.68   246.809774  489.871263   55.512479  324.000000
3         5.60   280.160019  488.014239   53.852162  391.000000
4         5.96   375.453033  486.014239   62.682686  316.000000
..         ...          ...         ...         ...         ...
195       9.36  1090.970881  303.833203   98.235076  242.000000
196       9.36  1008.665195  303.195604  100.961929  332.000000
197       9.36   922.633308  302.902043   98.726845  322.000000
198       9.36   926.464082  301.902043  104.573169  280.000000
199       9.36  1075.453986  301.264950  102.445120  458.000000

         mean_cash  period
0       748.885497       0
1      1190.512599       1
2      1627.663829       2
3      2042.206109       3
4      2502.831312       4
..             ...     ...
195  151210.244208     195
196  152000.706831     196
197  152770.841344     197
198  153595.318286     198
199  154341.994214     199

[200 rows x 7 columns]), ((False, 25, 0.35, 0.5, 0.33, 0.005, 4),      mean_tech  total_lobby     n_allow  mean_prod   emissions      mean_cash  \
0         3.92     0.000000  431.000000  81.566594  663.209839     815.665939
1         4.00   140.381942  429.000000  57.256488  341.000000    1234.190823
2         4.60   212.990676  427.000000  60.231868  298.000000    1691.029940
3         5.56   278.290045  425.248843  60.944920  309.000000    2135.292879
4         6.20   338.111926  423.896972  68.343835  190.000000    2647.846797
..         ...          ...         ...        ...         ...            ...
195       9.44   690.806906  271.197030  91.687151  215.000000  145753.173138
196       9.44   775.084737  270.197030  94.893582  368.000000  146464.943096
197       9.44   682.388489  269.197030  88.263677  471.000000  147138.006587
198       9.44   610.623366  268.522721  87.759357  244.000000  147803.911068
199       9.44   580.195250  268.310848  95.966056  245.000000  148555.571290

     period
0         0
1         1
2         2
3         3
4         4
..      ...
195     195
196     196
197     197
198     198
199     199

[200 rows x 7 columns]), ((False, 25, 0.35, 0.5, 0.33, 0.005, 8),      mean_tech  total_lobby     n_allow  mean_prod   emissions      mean_cash  \
0         3.52     0.000000  506.000000  71.005050  778.754014     710.050500
1         3.60   141.157552  505.629574  50.114957  355.000000    1088.328487
2         4.36   204.245258  503.854668  48.544598  354.000000    1456.171088
3         5.28   277.939431  503.591639  52.094011  333.000000    1842.065031
4         5.84   265.305006  501.963334  57.732999  306.000000    2318.078226
..         ...          ...         ...        ...         ...            ...
195       9.32  1530.867294  313.589516  89.832323  270.000000  148346.534134
196       9.32  1422.119220  312.589516  86.410668  350.000000  148979.525108
197       9.32  1376.934895  311.816841  84.695250  520.000000  149590.372840
198       9.32  1374.012924  311.146502  86.481891  232.000000  150211.770768
199       9.32  1370.628003  310.762666  87.082497  229.000000  150852.294213

     period
0         0
1         1
2         2
3         3
4         4
..      ...
195     195
196     196
197     197
198     198
199     199

[200 rows x 7 columns]), ((False, 25, 0.35, 0.5, 0.33, 0.005, 6),      mean_tech  total_lobby     n_allow   mean_prod   emissions  \
0         3.76     0.000000  580.000000   71.271330  893.477974
1         3.84   221.588701  578.000000   58.014131  410.000000
2         4.20   429.759973  576.332896   62.119840  424.000000
3         5.16   485.013166  574.332896   58.913291  478.000000
4         5.92   600.086083  572.612463   68.999357  270.000000
..         ...          ...         ...         ...         ...
195       9.48  2645.988231  351.434346  113.037128  324.000000
196       9.48  2871.866154  350.434346  111.229753  503.000000
197       9.48  2442.319232  350.310267  109.827735  323.000000
198       9.48  2210.973847  349.484147  104.699470  382.000000
199       9.48  1819.203490  348.484147  101.561324  488.000000

         mean_cash  period
0       712.713298       0
1      1139.518426       1
2      1590.750471       2
3      2034.124431       3
4      2563.452861       4
..             ...     ...
195  159630.452368     195
196  160450.582525     196
197  161309.306492     197
198  162119.178889     198
199  162927.123225     199

[200 rows x 7 columns]), ((False, 25, 0.35, 0.5, 0.33, 0.005, 7),      mean_tech  total_lobby     n_allow   mean_prod   emissions  \
0         3.84     0.000000  585.000000   79.870161  901.077488
1         3.88   212.511531  583.356740   62.334208  473.000000
2         4.64   307.709369  581.356740   55.305355  424.000000
3         5.60   388.457454  579.572613   61.889869  412.000000
4         6.12   505.800672  578.685155   77.995903  418.000000
..         ...          ...         ...         ...         ...
195       9.76  2187.473105  350.986302  109.185817  308.000000
196       9.76  2091.092357  350.228429  101.969952  396.000000
197       9.76  2241.654389  349.367265  112.151089  315.000000
198       9.76  2200.048146  348.367265  110.688034  438.000000
199       9.76  2336.588896  348.180493  109.100946  399.000000

         mean_cash  period
0       798.701610       0
1      1255.532667       1
2      1667.813357       2
3      2139.436691       3
4      2749.611488       4
..             ...     ...
195  167532.140728     195
196  168292.178615     196
197  169134.967766     197
198  169975.274343     198
199  170779.427146     199

[200 rows x 7 columns]), ((False, 25, 0.35, 0.5, 0.33, 0.005, 1),      mean_tech  total_lobby     n_allow   mean_prod    emissions  \
0         4.16     0.000000  663.000000   78.386738  1021.479124
1         4.28   241.280951  662.128410   64.195962   469.000000
2         4.76   442.948357  660.062929   65.922795   460.000000
3         5.60   662.958006  657.472510   71.432777   409.000000
4         6.24   691.159501  654.472510   73.144026   396.000000
..         ...          ...         ...         ...          ...
195       9.72  2915.932287  383.231508  120.701658   403.000000
196       9.72  2987.768924  382.793654  120.179541   446.000000
197       9.72  3056.442162  381.880613  121.482367   261.000000
198       9.72  2963.262658  381.581775  120.944779   523.000000
199       9.72  3317.566665  380.755677  119.720565   348.000000

         mean_cash  period
0       783.867378       0
1      1271.281737       1
2      1763.184405       2
3      2286.942788       3
4      2863.997777       4
..             ...     ...
195  172314.899998     195
196  173216.351356     196
197  174131.995351     197
198  175057.881177     198
199  175921.481628     199

[200 rows x 7 columns]), ((True, 25, 0.35, 0.5, 0.33, 0.005, 3),      mean_tech  total_lobby     n_allow   mean_prod  emissions    mean_cash  \
0         3.60     0.000000  484.000000   75.921340  745.28365   759.213399
1         3.60   179.126325  482.000000   56.245304  378.00000   723.473620
2         4.24   293.577764  480.000000   53.631643  477.00000   696.843090
3         5.12   508.596989  479.768853   65.819373  383.00000   733.099104
4         5.68   766.210346  479.504919   77.105576  448.00000   825.906501
..         ...          ...         ...         ...        ...          ...
195       9.36  2023.373913  298.273906  100.466200  367.00000  1164.862183
196       9.36  1902.903971  297.273906  100.572994  277.00000  1205.359113
197       9.36  1977.837886  296.273906   99.134966  224.00000  1182.560069
198       9.36  2071.425587  295.888519   99.032976  277.00000  1172.533929
199       9.36  2080.223975  294.888519   96.816205  373.00000  1162.090290

     period
0         0
1         1
2         2
3         3
4         4
..      ...
195     195
196     196
197     197
198     198
199     199

[200 rows x 7 columns]), ((True, 25, 0.35, 0.5, 0.33, 0.005, 4),      mean_tech  total_lobby     n_allow  mean_prod   emissions    mean_cash  \
0         4.84     0.000000  346.000000  88.454212  532.920909   884.542122
1         4.88   103.024982  345.000000  58.192279  252.000000   842.936047
2         5.36   172.304443  344.000000  56.357353  250.000000   786.363237
3         6.16   269.320510  343.749136  69.677483  249.000000   866.340469
4         6.68   359.067696  342.767232  73.874735  327.000000   908.054220
..         ...          ...         ...        ...         ...          ...
195       9.72   257.280912  208.302609  72.394691  180.000000  1023.520475
196       9.72   267.800205  208.017914  72.722260  193.000000  1009.889214
197       9.72   341.581738  207.251779  89.662049  246.000000  1144.247081
198       9.72   297.668211  207.097418  73.896250  221.000000  1112.938988
199       9.72   257.830867  206.097418  68.744318  199.000000  1047.321766

     period
0         0
1         1
2         2
3         3
4         4
..      ...
195     195
196     196
197     197
198     198
199     199

[200 rows x 7 columns]), ((True, 25, 0.35, 0.5, 0.33, 0.005, 0),      mean_tech  total_lobby     n_allow  mean_prod   emissions    mean_cash  \
0         4.56     0.000000  364.000000  84.571508  560.677633   845.715084
1         4.68   132.244627  363.000000  64.038270  297.000000   863.286116
2         5.12   223.218648  362.579478  54.202426  341.000000   769.324783
3         5.84   310.124126  362.140140  63.400215  328.000000   808.001253
4         6.32   445.124455  361.140140  75.155824  299.000000   897.805029
..         ...          ...         ...        ...         ...          ...
195       9.60   762.139200  227.400370  67.294086  275.000000  1059.318635
196       9.60   818.978338  226.961969  77.720361  185.000000  1049.492290
197       9.60   856.601889  225.961969  83.594785  194.000000  1104.823564
198       9.60   822.986589  225.712648  80.512668  209.000000  1108.049695
199       9.60   680.412674  225.013749  86.963046  249.000000  1188.714886

     period
0         0
1         1
2         2
3         3
4         4
..      ...
195     195
196     196
197     197
198     198
199     199

[200 rows x 7 columns]), ((True, 25, 0.35, 0.5, 0.33, 0.005, 2),      mean_tech  total_lobby     n_allow   mean_prod  emissions    mean_cash  \
0         3.56     0.000000  595.000000   73.339454  915.87372   733.394539
1         3.64   222.660414  594.113413   55.057435  466.00000   618.288005
2         4.16   403.677288  592.113413   66.011133  379.00000   696.688703
3         5.16   605.857267  590.766783   63.356072  623.00000   656.550151
4         6.00   705.855755  589.880034   68.557200  474.00000   694.351403
..         ...          ...         ...         ...        ...          ...
195       9.60  2664.848979  360.767899  112.515487  378.00000  1253.109605
196       9.60  3096.063029  360.009872  112.867422  349.00000  1192.109819
197       9.60  2927.255899  359.009872  116.770794  502.00000  1262.206232
198       9.60  3646.363213  358.009872  117.121602  382.00000  1216.111803
199       9.60  3980.205637  357.009872  119.461984  535.00000  1237.637974

     period
0         0
1         1
2         2
3         3
4         4
..      ...
195     195
196     196
197     197
198     198
199     199

[200 rows x 7 columns]), ((True, 25, 0.35, 0.5, 0.33, 0.005, 1),      mean_tech  total_lobby     n_allow   mean_prod    emissions    mean_cash  \
0         3.64     0.000000  715.000000   69.246130  1101.135464   692.461304
1         3.64   279.262413  714.331686   58.945049   405.000000   600.082109
2         4.36   434.357882  712.064135   59.302558   528.000000   616.351253
3         5.32   517.196512  709.064135   68.174932   446.000000   688.986798
4         5.68   786.853234  706.801675   77.807955   609.000000   733.061344
..         ...          ...         ...         ...          ...          ...
195       9.44  2795.758136  391.022585  118.144969   400.000000  1234.449024
196       9.44  2801.025340  390.022585  118.010555   298.000000  1224.813221
197       9.44  2825.524448  389.873901  114.638152   373.000000  1186.443596
198       9.44  2821.817196  389.221685  118.728725   575.000000  1210.499478
199       9.44  2796.360411  388.758837  117.356169   406.000000  1223.428569

     period
0         0
1         1
2         2
3         3
4         4
..      ...
195     195
196     196
197     197
198     198
199     199

[200 rows x 7 columns]), ((True, 25, 0.35, 0.5, 0.33, 0.005, 5),      mean_tech  total_lobby     n_allow   mean_prod    emissions    mean_cash  \
0         4.68     0.000000  819.000000   91.662610  1260.770042   916.626101
1         4.72   346.001585  817.331866   74.518377   555.000000   749.558295
2         5.16   502.950959  813.433357   81.850941   584.000000   833.461314
3         5.96   875.717577  812.784366   83.878041   588.000000   782.611196
4         6.40  1211.042375  809.456327   96.373339   687.000000   865.177098
..         ...          ...         ...         ...          ...          ...
195      10.12  4347.746069  475.202703  138.480000   433.000000  1335.117786
196      10.12  4344.628363  474.065117  138.480000   463.000000  1340.248516
197      10.12  3980.228507  472.065117  138.480000   511.000000  1388.247169
198      10.12  3703.312039  471.153007  138.480000   404.000000  1406.377476
199      10.12  3822.574916  469.153007  138.085337   600.000000  1381.580902

     period
0         0
1         1
2         2
3         3
4         4
..      ...
195     195
196     196
197     197
198     198
199     199

[200 rows x 7 columns]), ((True, 25, 0.35, 0.5, 0.33, 0.005, 8),      mean_tech  total_lobby     n_allow   mean_prod   emissions    mean_cash  \
0         3.40     0.000000  473.000000   68.698858  729.105061   686.988582
1         3.44   135.271198  471.358961   51.873182  304.000000   645.558241
2         3.96   145.237557  470.157758   45.303121  351.000000   610.946883
3         4.60   252.524865  469.772493   55.475233  425.000000   619.801132
4         5.12   386.177580  467.772493   68.360098  368.000000   716.798331
..         ...          ...         ...         ...         ...          ...
195       9.36  1994.788126  301.443761  102.052876  289.000000  1160.476100
196       9.36  1879.535674  300.443761   91.392213  314.000000  1092.613360
197       9.36  1812.074457  300.090112   94.705515  284.000000  1089.888884
198       9.36  1684.679031  299.263640   93.642624  476.000000  1109.363166
199       9.36  1657.214307  299.047062   92.176275  313.000000  1070.154409

     period
0         0
1         1
2         2
3         3
4         4
..      ...
195     195
196     196
197     197
198     198
199     199

[200 rows x 7 columns]), ((True, 25, 0.35, 0.5, 0.33, 0.005, 6),      mean_tech  total_lobby     n_allow   mean_prod   emissions    mean_cash  \
0         3.76     0.000000  777.000000   79.861506  1195.95526   798.615059
1         3.96   320.435220  774.000000   68.598479   481.00000   703.329933
2         4.56   480.259610  772.703302   71.615212   476.00000   744.311870
3         5.40   784.296108  769.703302   82.125160   519.00000   795.995071

In [7]:
lst = []
for key, value in od.items():
    auction = [key[0] for i in range(len(value.mean_tech))]
    iteration = [key[6] for i in range(len(value))]
    value["Auction"] = auction
    value["Iteration"] = iteration
    lst.append(value)

In [8]:
df = pd.concat(lst)

In [9]:
df

,mean_tech,total_lobby,n_allow,mean_prod,emissions,mean_cash,period,Auction,Iteration
0,4.44,0.000000,631.000000,71.913116,971.035036,719.131159,0,False,9
1,4.44,254.949229,628.606792,61.821870,411.000000,1179.308715,1,False,9
2,4.92,475.786309,627.603013,55.484322,381.000000,1567.090986,2,False,9
3,5.92,521.105783,626.586902,57.549445,341.000000,1999.776387,3,False,9
4,6.40,718.879193,624.190950,67.479501,284.000000,2502.216613,4,False,9
...,...,...,...,...,...,...,...,...,...
195,9.08,3452.247842,460.103274,116.880407,473.000000,1075.839270,195,True,7
196,9.08,3057.607270,458.920300,116.836762,505.000000,1126.730782,196,True,7
197,9.08,2875.514361,457.981499,117.052044,495.000000,1136.082268,197,True,7
198,9.08,2803.464039,456.104349,116.832993,625.000000,1128.113476,198,True,7
199,9.08,3355.432078,455.720054,116.853899,307.000000,1068.872780,199,True,7

In [10]:
#df.to_csv("out_data/AuctionExperiment.csv")

Cap Size and Decrement Experiment

In [2]:
#Experiment 2 Variables 
fixed_params2 = {
  "N": 25,
  "am": True,
  "mSize":  .5,
  "lobby": .33,
}
variable_params2 = {
  "cap_size": [.1, .2, .3, .4, .5, .6, .7, .8, .9],
  "dec": np.arange(.001, .01, .001)
}

In [3]:
experiment2 = BatchRunnerMP(Environment,
    nr_processes= None,
    variable_parameters = variable_params2, 
    fixed_parameters = fixed_params2,
    iterations = 1,
    max_steps = 200)

BatchRunner MP will use 16 processors.

In [4]:
experiment2.run_all()

81it [00:42,  1.91it/s]

(None,
 None,
 OrderedDict([((0.1, 0.001, 25, True, 0.5, 0.33, 0),
                    mean_tech  total_lobby  n_allow   mean_prod   emissions    mean_cash  \
               0         3.72     0.000000    489.0   76.576708  544.372772   765.767081
               1         3.76    32.617869    489.0   57.152407  334.000000   704.295487
               2         4.16    60.318728    489.0   62.079513  405.000000   726.188331
               3         4.96    83.272349    489.0   67.129166  377.000000   769.214866
               4         5.36   133.695127    489.0   71.354504  380.000000   744.988459
               ..         ...          ...      ...         ...         ...          ...
               195       8.76  2049.342502    489.0  106.080000  409.000000   980.144982
               196       8.76  2057.935334    489.0  106.080000  339.000000   968.135325
               197       8.76  1886.568870    489.0  106.080000  512.000000   999.446028
               198       8.76  1847.304008    489.0  106.080000  493.000000   986.835236
               199       8.76  1650.397320    489.0  106.080000  321.000000  1022.104989

                    period
               0         0
               1         1
               2         2
               3         3
               4         4
               ..      ...
               195     195
               196     196
               197     197
               198     198
               199     199

               [200 rows x 7 columns]),
              ((0.2, 0.001, 25, True, 0.5, 0.33, 0),
                    mean_tech  total_lobby  n_allow   mean_prod   emissions    mean_cash  \
               0         5.52     0.000000    358.0   87.941924  448.472477   879.419237
               1         5.56    28.453548    358.0   62.427009  306.000000   806.311347
               2         6.00    55.246285    358.0   63.352867  292.000000   790.896527
               3         6.68    82.431589    358.0   69.319139  275.000000   828.043058
               4         7.08   118.021028    358.0   76.814306  254.000000   865.329927
               ..         ...          ...      ...         ...         ...          ...
               195       9.60  1947.687425    358.0  105.515896  365.000000  1120.694355
               196       9.60  2023.162791    358.0  110.032302  360.000000  1154.948747
               197       9.60  2083.990862    358.0  101.347618  458.000000  1074.378368
               198       9.60  2077.437469    358.0  106.520900  450.000000  1106.588440
               199       9.60  2100.843475    358.0  100.337831  351.000000  1048.293574

                    period
               0         0
               1         1
               2         2
               3         3
               4         4
               ..      ...
               195     195
               196     196
               197     197
               198     198
               199     199

               [200 rows x 7 columns]),
              ((0.1, 0.005, 25, True, 0.5, 0.33, 0),
                    mean_tech  total_lobby     n_allow   mean_prod   emissions    mean_cash  \
               0         3.96     0.000000  723.000000   78.896724  804.167354   788.967238
               1         4.04   276.751262  720.550774   66.244143  472.000000   683.735341
               2         4.56   495.992734  717.550774   72.169264  433.000000   723.639685
               3         5.48   673.236644  714.550774   74.828108  548.000000   737.193535
               4         6.16   899.796966  711.550774   81.252372  503.000000   771.530945
               ..         ...          ...         ...         ...         ...          ...
               195       9.60  2889.438821  407.359941  118.421878  423.000000  1195.221943
               196       9.60  3314.228989  406.570705  119.077338  336.000000  1163.657825
               197       9.60  2978.919146  405.407574  119.284694  520.000000  1227.039653
               198       9.60  2934.473184  403.407574  118.548288  621.000000  1211.462935
               199       9.60  2825.419173  401.407574  122.693116  272.000000  1272.200810

                    period
               0         0
               1         1
               2         2
               3         3
               4         4
               ..      ...
               195     195
               196     196
               197     197
               198     198
               199     199

               [200 rows x 7 columns]),
              ((0.2, 0.007, 25, True, 0.5, 0.33, 0),
                    mean_tech  total_lobby     n_allow   mean_prod   emissions    mean_cash  \
               0         4.60     0.000000  624.000000   85.078973  781.067832   850.789734
               1         4.64   317.789469  622.150630   70.061413  407.000000   736.573203
               2         5.16   614.902297  618.934701   75.227228  425.000000   751.770016
               3         5.92  1014.770745  614.934701   81.340803  649.000000   784.216202
               4         6.48  1283.138255  613.613661   91.186676  404.000000   884.867905
               ..         ...          ...         ...         ...         ...          ...
               195       9.60  1527.030012  274.097954   97.337144  290.000000  1207.005499
               196       9.60  1495.022970  273.929349   92.461722  320.000000  1140.260467
               197       9.60  1419.424789  273.708715   95.407518  277.000000  1168.549844
               198       9.60  1524.375430  273.348660   97.789108  188.000000  1173.497755
               199       9.60  1780.032571  272.348660  100.307061  360.000000  1185.897094

                    period
               0         0
               1         1
               2         2
               3         3
               4         4
               ..      ...
               195     195
               196     196
               197     197
               198     198
               199     199

               [200 rows x 7 columns]),
              ((0.1, 0.007, 25, True, 0.5, 0.33, 0),
                    mean_tech  total_lobby     n_allow   mean_prod    emissions    mean_cash  \
               0         4.68     0.000000  904.000000   80.386452  1004.891238   803.864516
               1         4.80   556.171886  898.000000   74.210531   558.000000   666.027806
               2         5.52   959.854720  892.000000   76.320099   689.000000   672.409597
               3         6.40  1332.524141  886.000000   84.288723   530.000000   724.083059
               4         6.96  1887.887491  883.178595   95.205571   490.000000   797.800946
               ..         ...          ...         ...         ...          ...          ...
               195       9.80  4138.565104  372.072592  116.931300   573.000000  1177.534340
               196       9.80  4235.293406  371.151158  117.156217   336.000000  1183.891876
               197       9.80  3862.271208  370.401631  117.680000   317.000000  1227.731809
               198       9.80  3527.973793  369.828152  117.365061   429.000000  1250.896843
               199       9.80  3384.257400  367.828152  116.220905   345.000000  1247.857420

                    period
               0         0
               1         1
               2         2
               3         3
               4         4
               ..      ...
               195     195
               196     196
               197     197
               198     198
               199     199

               [200 rows x 7 columns]),
              ((0.1, 0.009000000000000001, 25, True, 0.5, 0.33, 0),
                    mean_tech  total_lobby     n_allow   mean_prod   emissions    mean_cash  \
               0         4.64     0.000000  748.000000   76.466794  831.282789   764.667940
               1         4.68   534.239254  746.170516   66.604625  443.000000   649.388859
               2         5.24   913.192743  743.699049   68.088685  460.000000   646.539900
               3         6.04  1236.490482  739.498586   74.176318  645.000000   676.387973
               4         6.56  1632.639094  733.498586   84.937511  472.000000   739.892912
               ..         ...          ...         ...         ...         ...          ...
               195       9.76  2295.814005  254.359734   99.943384  314.000000  1250.398917
               196       9.76  2221.151877  253.651403  100.705302  253.000000  1280.357612
               197       9.76  1913.988577  251.651403   95.130038  256.000000  1261.614573
               198       9.76  1714.470794  251.407029   94.788631  294.000000  1269.452760
               199       9.76  1964.195521  249.921896   91.058260  261.000000  1175.285509

                    period
               0         0
               1         1
               2         2
               3         3
               4         4
               ..      ...
               195     195
               196     196
               197     197
               198     198
               199     199

               [200 rows x 7 columns]),
              ((0.2, 0.006, 25, True, 0.5, 0.33, 0),
                    mean_tech  total_lobby     n_allow   mean_prod   emissions    mean_cash  \
               0         3.68     0.000000  643.000000   70.192094  804.635932   701.920936
               1         3.72   278.796823  640.000000   56.621010  471.000000   621.908835
               2         4.24   423.078785  637.000000   54.344094  637.000000   603.847714
               3         5.16   756.961768  634.397640   66.796724  443.000000   634.565549
               4         5.72   996.215366  632.406367   77.437627  398.000000   738.288729
               ..         ...          ...         ...         ...         ...          ...
               195       9.36  2145.884391  322.188358  110.165049  318.000000  1235.518443
               196       9.36  2381.946523  321.719996  106.245437  436.000000  1178.182440
               197       9.36  2516.448963  320.719996  107.448854  316.000000  1172.316191
               198       9.36  2382.330580  320.057574   99.370257  346.000000  1114.873161
               199       9.36  2670.640789  319.057574  108.886605  371.000000  1161.073540

                    period
               0         0
               1         1
               2         2
               3         3
               4         4
               ..      ...
               195     195
               196     196
               197     197
               198     198
               199     199

               [200 rows x 7 columns]),
              ((0.1, 0.008, 25, True, 0.5, 0.33, 0),
                    mean_tech  total_lobby     n_allow   mean_prod   emissions    mean_cash  \
               0         4.20     0.000000  867.000000   75.401086  964.371978   754.010857
               1         4.36   487.278855  866.385726   58.976448  585.000000   542.326771
               2         4.80   963.376533  860.385726   74.217475  408.000000   628.604131
               3         5.68  1412.371701  858.787656   78.142755  415.000000   635.712916
               4         6.32  1529.697233  854.821636   86.939988  417.000000   741.184179
               ..         ...          ...         ...         ...         ...          ...
               195       9.00  2261.554767  336.023963  109.700432  474.000000  1180.944469
               196       9.00  2523.567284  334.023963  109.965651  370.000000  1166.922540
               197       9.00  2512.784817  332.023963  109.501102  231.000000  1166.337345
               198       9.00  2394.794746  331.634845  109.344621  404.000000  1188.778254
               199       9.00  2761.082752  330.932566  109.944542  324.000000  1148.874044

                    period
               0         0
               1         1
               2         2
               3         3
               4         4
               ..      ...
               195     195
               196     196
               197     197
               198     198
               199     199

               [200 rows x 7 columns]),
              ((0.2, 0.003, 25, True, 0.5, 0.33, 0),
                    mean_tech  total_lobby     n_allow   mean_prod   emissions    mean_cash  \
               0         4.32     0.000000  633.000000   75.144980  791.794995   751.449798
               1         4.36   165.215901  632.790140   59.113801  512.000000   639.324556
               2         4.88   279.574106  632.052449   61.068508  530.000000   655.704849
               3         5.68   427.123250  631.052449   69.820089  455.000000   695.530481
               4         6.20   640.560284  630.052449   79.198445  493.000000   763.800933
               ..         ...          ...         ...         ...         ...          ...
               195       9.64  2919.902563  492.609817  117.560000  540.000000  1109.366093
               196       9.64  3231.166153  491.609817  117.560000  621.000000  1075.037800
               197       9.64  3353.738440  491.129734  117.560000  410.000000  1066.780241
               198       9.64  3188.399710  490.392398  117.560000  678.000000  1104.922385
               199       9.64  3177.912572  489.392398  116.974774  480.000000  1088.265825

                    period
               0         0
               1         1
               2         2
               3         3
               4         4
               ..      ...
               195     195
               196     196
               197     197
               198     198
               199     199

               [200 rows x 7 columns]),
              ((0.2, 0.005, 25, True, 0.5, 0.33, 0),
                    mean_tech  total_lobby     n_allow   mean_prod   emissions    mean_cash  \
               0         3.76     0.000000  752.000000   77.453974  940.433018   774.539742
               1         3.84   277.668541  750.678522   64.713026  459.000000   676.700310
               2         4.36   514.515813  747.678522   67.895755  599.000000   692.394837
               3         5.28   785.158792  746.664315   74.964782  602.000000   712.762158
               4         5.96  1177.431044  743.664315   82.076246  675.000000   739.965029
               ..         ...          ...         ...         ...         ...          ...
               195       9.68  3077.536117  430.287943  124.095084  645.000000  1278.188550
               196       9.68  3247.400294  430.085574  124.653747  328.000000  1246.881074
               197       9.68  3248.067868  428.498938  124.232049  489.000000  1258.201639
               198       9.68  3072.900162  426.498938  125.167224  504.000000  1283.937255
               199       9.68  3419.270258  424.498938  124.461848  477.000000  1250.153721

                    period
               0         0
               1         1
               2         2
               3         3
               4         4
               ..      ...
               195     195
               196     196
               197     197
               198     198
               199     199

               [200 rows x 7 columns]),
              ((0.1, 0.003, 25, True, 0.5, 0.33, 0),
                    mean_tech  total_lobby     n_allow   mean_prod    emissions    mean_cash  \
               0         3.92     0.000000  922.000000   71.053011  1024.564666   710.530106
               1         3.96   228.088787  921.291451   66.435174   551.000000   594.593180
               2         4.60   359.614657  919.291451   65.854362   515.000000   600.811843
               3         5.56   462.554438  918.706240   73.047155   692.000000   656.974015
               4         6.04   676.889694  917.153273   85.715524   477.000000   740.333340
               ..         ...          ...         ...         ...          ...          ...
               195       9.44  2935.556116  655.545209  118.040000   406.000000   984.035693
               196       9.44  3040.726717  654.982553  118.040000   357.000000   975.423357
               197       9.44  3401.689946  654.078577  118.040000   627.000000   934.678218
               198       9.44  3140.777691  653.610281  118.040000   409.000000   989.795291
               199       9.44  2814.106407  653.041943  118.040000   524.000000  1015.593086

                    period
               0         0
               1         1
               2         2
               3         3
               4         4
               ..      ...
               195     195
               196     196
               197     197
               198     198
               199     199

               [200 rows x 7 columns]),
              ((0.2, 0.004, 25, True, 0.5, 0.33, 0),
                    mean_tech  total_lobby     n_allow   mean_prod   emissions    mean_cash  \
               0         4.44     0.000000  772.000000   85.688760  966.152163   856.887596
               1         4.44   226.946258  770.506926   71.879224  538.000000   720.364260
               2         5.04   416.155216  767.506926   75.288581  533.000000   728.375870
               3         5.84   653.822494  764.506926   83.444063  545.000000   760.779905
               4         6.40   965.197418  761.506926   93.148250  514.000000   810.068380
               ..         ...          ...         ...         ...         ...          ...
               195       9.76  3426.424863  498.230382  129.200000  603.000000  1228.069469
               196       9.76  3718.139453  497.230382  129.200000  435.000000  1209.703825
               197       9.76  3771.854808  496.757414  129.200000  736.000000  1203.806917
               198       9.76  3262.847134  495.757414  129.200000  264.000000  1257.714936
               199       9.76  2889.769809  494.757414  129.200000  495.000000  1279.697005

                    period
               0         0
               1         1
               2         2
               3         3
               4         4
               ..      ...
               195     195
               196     196
               197     197
               198     198
               199     199

               [200 rows x 7 columns]),
              ((0.1, 0.006, 25, True, 0.5, 0.33, 0),
                    mean_tech  total_lobby     n_allow   mean_prod   emissions    mean_cash  \
               0         3.80     0.000000  874.000000   74.423601  971.592831   744.236007
               1         3.84   392.940434  871.002048   69.136362  536.000000   690.372950
               2         4.32   708.028505  868.104698   66.408833  717.000000   649.159967
               3         5.24  1076.174574  866.364373   77.582189  450.000000   700.097921
               4         5.88  1573.542543  861.364373   85.751123  567.000000   728.477186
               ..         ...          ...         ...         ...         ...          ...
               195       9.44  3357.208114  439.203872  123.200000  509.000000  1205.799385
               196       9.44  3659.533540  438.555866  122.719186  847.000000  1196.358349
               197       9.44  3328.566171  436.555866  122.406610  465.000000  1226.763065
               198       9.44  3318.111814  434.862918  122.427187  440.000000  1222.379598
               199       9.44  3331.753638  432.935351  122.580859  745.000000  1215.453344

                    period
               0         0
               1         1
               2         2
               3         3
               4         4
               ..      ...
               195     195
               196     196
               197     197
               198     198
               199     199

               [200 rows x 7 columns]),
              ((0.1, 0.002, 25, True, 0.5, 0.33, 0),
                    mean_tech  total_lobby     n_allow   mean_prod    emissions   mean_cash  \

In [5]:
dic = experiment2.get_collector_model()

In [6]:
len(list(dic.values()))

81

In [7]:
data = []
panel = 0
for key, value in dic.items():
    initial_cap = [key[0] for i in range(len(value))]
    decrement = [key[1] for i in range(len(value))]
    iteration = [key[6] for i in range(len(value))]
    value["init_cap"] = initial_cap
    value["decrement"] = decrement
    value["Iteration"] = iteration
    value["panel"] = [panel for i in range(len(value))]
    panel += 1
    data.append(value)

In [8]:
len(data)

81

In [9]:
df2 = pd.concat(data)

In [10]:
df2.to_csv("out_data/Cap_and_Dec_Experiment.csv")

Experiment 3: Cooperation Requirement

In [22]:
fixed_params3 = {
  "N": 25,
  "am": True,
  "mSize":  .5,
  "cap_size": .4,
  "dec": .005
}
variable_params3 = {
  "lobby": np.arange(.1, .9, .1)
}

In [26]:
experiment3 = BatchRunnerMP(Environment,
    nr_processes= None,
    variable_parameters = variable_params3, 
    fixed_parameters = fixed_params3,
    iterations = 10,
    max_steps = 200)

BatchRunner MP will use 16 processors.

In [27]:
experiment3.run_all()

80it [00:42,  1.89it/s]

(None,
 None,
 OrderedDict([((0.1, 25, True, 0.5, 0.4, 0.005, 0),
                    mean_tech  total_lobby     n_allow  mean_prod   emissions    mean_cash  \
               0         3.36     0.000000  476.000000  76.909420  794.842189   769.094197
               1         3.40   132.929517  474.000000  55.891386  380.000000   766.324341
               2         4.04   336.125069  472.370522  56.839832  353.000000   766.428589
               3         4.88   640.430751  470.370522  62.688733  380.000000   793.291583
               4         5.24  1155.989407  468.370522  73.251428  469.000000   846.537546
               ..         ...          ...         ...        ...         ...          ...
               195       7.96  3541.636356  301.328122  91.381342  384.000000  1138.936126
               196       7.96  4060.779818  301.033809  93.303859  351.000000  1116.388771
               197       7.96  4597.243646  300.191638  96.007547  327.000000  1119.547376
               198       7.96  4098.477586  299.960917  93.377340  301.000000  1134.492898
               199       7.96  3484.273995  299.690767  95.454140  331.000000  1192.415389

                    period
               0         0
               1         1
               2         2
               3         3
               4         4
               ..      ...
               195     195
               196     196
               197     197
               198     198
               199     199

               [200 rows x 7 columns]),
              ((0.1, 25, True, 0.5, 0.4, 0.005, 4),
                    mean_tech  total_lobby     n_allow   mean_prod    emissions    mean_cash  \
               0         3.68     0.000000  619.000000   70.751024  1032.796356   707.510242
               1         3.76   210.767570  617.471955   55.954392   421.000000   613.749473
               2         4.40   484.212624  614.938314   58.196409   432.000000   631.498891
               3         5.24  1031.086146  613.195109   66.381332   448.000000   659.444031
               4         5.84  1683.545385  612.214556   75.165498   560.000000   735.255045
               ..         ...          ...         ...         ...          ...          ...
               195       8.80  4866.935291  374.300700  109.975788   364.000000  1189.341361
               196       8.80  4564.521264  374.170003  109.501958   407.000000  1199.584348
               197       8.80  4145.978529  373.637371  108.590627   375.000000  1212.062010
               198       8.80  4776.787326  372.637371  104.905015   507.000000  1131.932889
               199       8.80  4120.541743  372.136462  108.671279   395.000000  1195.291696

                    period
               0         0
               1         1
               2         2
               3         3
               4         4
               ..      ...
               195     195
               196     196
               197     197
               198     198
               199     199

               [200 rows x 7 columns]),
              ((0.1, 25, True, 0.5, 0.4, 0.005, 7),
                    mean_tech  total_lobby     n_allow   mean_prod   emissions    mean_cash  \
               0         5.16     0.000000  464.000000  103.559768  774.549668  1035.597683
               1         5.24   150.205397  463.742540   76.776722  352.000000  1016.228325
               2         5.64   473.356532  462.334691   76.774900  393.000000   982.594714
               3         6.44  1057.323714  461.670892   81.941590  360.000000   997.042525
               4         7.04  1941.812298  459.670892   93.043860  422.000000  1054.094167
               ..         ...          ...         ...         ...         ...          ...
               195       9.36  4629.513067  294.478921  108.552113  318.000000  1377.024959
               196       9.36  4393.585547  294.174260  105.517926  285.000000  1364.904338
               197       9.36  4189.098392  293.861847  107.599760  263.000000  1395.263504
               198       9.36  4472.887379  292.861847  112.530129  253.000000  1431.367508
               199       9.36  4397.352104  292.408273  107.608875  310.000000  1420.148530

                    period
               0         0
               1         1
               2         2
               3         3
               4         4
               ..      ...
               195     195
               196     196
               197     197
               198     198
               199     199

               [200 rows x 7 columns]),
              ((0.1, 25, True, 0.5, 0.4, 0.005, 8),
                    mean_tech  total_lobby     n_allow  mean_prod   emissions    mean_cash  \
               0         4.08     0.000000  306.000000  81.849964  511.664544   818.499636
               1         4.16    77.884831  305.158670  44.761275  274.000000   768.907203
               2         4.52   234.391111  304.158670  53.844946  278.000000   813.580100
               3         5.36   375.653207  303.756909  43.813064  285.000000   749.947458
               4         5.84   702.226975  302.756909  53.816805  274.000000   745.174860
               ..         ...          ...         ...        ...         ...          ...
               195       8.28  2438.988016  199.593829  67.750344  182.000000  1000.864410
               196       8.28  2080.177411  199.593829  66.887456  216.000000  1027.237443
               197       8.28  2180.387721  199.593829  70.424439  188.000000  1052.884143
               198       8.28  2158.920968  199.593829  65.063527  154.000000  1010.253345
               199       8.28  2534.939671  199.593829  75.068427  179.000000  1060.581877

                    period
               0         0
               1         1
               2         2
               3         3
               4         4
               ..      ...
               195     195
               196     196
               197     197
               198     198
               199     199

               [200 rows x 7 columns]),
              ((0.2, 25, True, 0.5, 0.4, 0.005, 1),
                    mean_tech  total_lobby     n_allow  mean_prod   emissions    mean_cash  \
               0         3.92     0.000000  335.000000  64.306190  559.085841   643.061896
               1         3.92    81.798059  334.683366  42.694428  277.000000   621.992041
               2         4.28   210.421541  334.308356  40.403029  300.000000   561.058520
               3         4.96   297.558107  334.109352  47.705880  258.000000   624.181220
               4         5.56   432.758718  333.988669  47.809712  240.000000   604.486780
               ..         ...          ...         ...        ...         ...          ...
               195       8.00  1726.088476  199.645711  73.223691  202.000000  1019.656512
               196       8.00  1746.986555  199.645711  69.916566  192.000000   975.346868
               197       8.00  1687.751850  199.645711  68.238776  208.000000   942.024208
               198       8.00  1578.125578  199.645711  72.518288  194.000000   980.258926
               199       8.00  1865.953501  199.645711  74.218951  170.000000   967.159391

                    period
               0         0
               1         1
               2         2
               3         3
               4         4
               ..      ...
               195     195
               196     196
               197     197
               198     198
               199     199

               [200 rows x 7 columns]),
              ((0.1, 25, True, 0.5, 0.4, 0.005, 6),
                    mean_tech  total_lobby     n_allow   mean_prod   emissions    mean_cash  \
               0         3.88     0.000000  549.000000   78.382196  916.593853   783.821960
               1         3.92   204.260603  547.000000   65.537609  415.000000   762.708413
               2         4.44   447.796473  545.505428   63.854996  450.000000   767.638072
               3         5.20  1142.571481  543.505428   73.407241  312.000000   765.429313
               4         5.72  1846.379006  542.492815   76.028962  485.000000   792.619535
               ..         ...          ...         ...         ...         ...          ...
               195       8.40  3983.850656  334.279888  101.594147  311.000000  1169.327591
               196       8.40  4065.853249  333.279888  101.115530  330.000000  1166.304334
               197       8.40  4563.307848  332.859552  102.298582  411.000000  1149.888467
               198       8.40  5115.345031  331.859552  104.195004  330.000000  1151.476623
               199       8.40  4533.270675  331.289089  101.938667  407.000000  1168.680593

                    period
               0         0
               1         1
               2         2
               3         3
               4         4
               ..      ...
               195     195
               196     196
               197     197
               198     198
               199     199

               [200 rows x 7 columns]),
              ((0.1, 25, True, 0.5, 0.4, 0.005, 2),
                    mean_tech  total_lobby     n_allow  mean_prod   emissions    mean_cash  \
               0         4.52     0.000000  555.000000  81.339163  925.359146   813.391634
               1         4.52   218.566236  554.007781  58.472023  447.000000   676.823168
               2         4.92   679.546429  552.234839  69.667288  403.000000   730.983896
               3         5.80  1332.567447  550.234839  75.833185  509.000000   789.937817
               4         6.60  2122.473573  548.733851  82.693412  436.000000   837.442383
               ..         ...          ...         ...        ...         ...          ...
               195       8.84  4028.584437  332.631778  96.531800  318.000000  1083.426159
               196       8.84  4136.532760  332.435421  93.931723  402.000000  1064.109132
               197       8.84  4129.905597  331.435421  94.755859  292.000000  1060.750660
               198       8.84  4012.724900  330.643329  98.424270  273.000000  1106.236302
               199       8.84  4831.761634  329.733374  96.231829  455.000000  1049.197812

                    period
               0         0
               1         1
               2         2
               3         3
               4         4
               ..      ...
               195     195
               196     196
               197     197
               198     198
               199     199

               [200 rows x 7 columns]),
              ((0.2, 25, True, 0.5, 0.4, 0.005, 3),
                    mean_tech  total_lobby     n_allow  mean_prod  emissions   mean_cash  \
               0         3.56     0.000000  383.000000  60.169513  639.87176  601.695133
               1         3.60   106.902981  382.670567  39.089832  311.00000  520.882364
               2         4.08   256.070548  381.987423  45.968401  304.00000  549.711705
               3         4.92   388.090605  380.987423  47.603979  344.00000  571.676246
               4         5.36   649.220365  380.696253  55.965239  252.00000  607.868419
               ..         ...          ...         ...        ...        ...         ...
               195       7.88  2587.055413  239.071790  74.279110  214.00000  885.401895
               196       7.88  2276.102004  238.938267  75.539100  283.00000  923.735976
               197       7.88  2468.094236  238.160635  74.576425  245.00000  901.687788
               198       7.88  2731.086896  237.780647  77.366794  248.00000  899.885334
               199       7.88  2630.001769  236.780647  79.224222  297.00000  947.796277

                    period
               0         0
               1         1
               2         2
               3         3
               4         4
               ..      ...
               195     195
               196     196
               197     197
               198     198
               199     199

               [200 rows x 7 columns]),
              ((0.1, 25, True, 0.5, 0.4, 0.005, 5),
                    mean_tech  total_lobby     n_allow   mean_prod   emissions    mean_cash  \
               0         3.72     0.000000  593.000000   76.758548  989.021932   767.585482
               1         3.76   131.047508  591.000000   51.368959  512.000000   670.991748
               2         4.04   363.132924  589.000000   53.558588  422.000000   631.603281
               3         4.88   843.818793  587.211989   63.432365  474.000000   664.067450
               4         5.60  1406.122162  586.134590   68.512300  449.000000   712.689631
               ..         ...          ...         ...         ...         ...          ...
               195       9.00  4895.575561  358.280192  112.000103  368.000000  1268.935975
               196       9.00  4933.746641  357.678718  110.255382  492.000000  1263.373476
               197       9.00  4671.884611  356.678718  107.324178  406.000000  1245.110120
               198       9.00  4797.516016  355.678718  109.405039  316.000000  1250.129353
               199       9.00  4114.487447  355.187379  102.757420  390.000000  1220.374269

                    period
               0         0
               1         1
               2         2
               3         3
               4         4
               ..      ...
               195     195
               196     196
               197     197
               198     198
               199     199

               [200 rows x 7 columns]),
              ((0.1, 25, True, 0.5, 0.4, 0.005, 1),
                    mean_tech  total_lobby     n_allow   mean_prod    emissions    mean_cash  \
               0         3.92     0.000000  665.000000   77.254615  1109.896896   772.546150
               1         4.04   245.859647  664.133236   69.760440   411.000000   756.642757
               2         4.52   683.516135  663.754124   62.965052   560.000000   685.480600
               3         5.48  1151.614943  661.398803   65.043760   566.000000   674.467442
               4         6.04  2490.822651  658.398803   88.273314   509.000000   790.898504
               ..         ...          ...         ...         ...          ...          ...
               195       8.96  5336.000570  379.969641  110.904906   557.000000  1202.044795
               196       8.96  4785.717995  379.678853  113.014767   431.000000  1238.349228
               197       8.96  5132.813999  378.678853  107.172950   330.000000  1157.263597
               198       8.96  5015.748489  377.835666  110.274993   572.000000  1179.546504
               199       8.96  4612.749279  376.835666  108.408743   392.000000  1185.226022

                    period
               0         0
               1         1
               2         2
               3         3
               4         4
               ..      ...
               195     195
               196     196
               197     197
               198     198
               199     199

               [200 rows x 7 columns]),
              ((0.1, 25, True, 0.5, 0.4, 0.005, 9),
                    mean_tech  total_lobby     n_allow   mean_prod   emissions    mean_cash  \
               0         4.60     0.000000  533.000000   88.521421  889.082349   885.214211
               1         4.80   220.404830  531.000000   71.298813  386.000000   842.835786
               2         5.40   565.441563  529.199177   73.064029  450.000000   869.729764
               3         6.36  1069.333093  527.398678   83.116850  379.000000   949.648663
               4         6.80  2385.844042  525.398678   95.384610  412.000000   980.079704
               ..         ...          ...         ...         ...         ...          ...
               195       9.08  4438.112132  327.058372  110.108694  221.000000  1306.138758
               196       9.08  4645.787421  326.103239   99.594405  354.000000  1214.780864
               197       9.08  4010.068693  325.103239   99.182917  315.000000  1206.880131
               198       9.08  4997.828383  324.129069  104.959792  287.000000  1194.462087
               199       9.08  4627.562801  323.873325  111.859690  331.000000  1308.742519

                    period
               0         0
               1         1
               2         2
               3         3
               4         4
               ..      ...
               195     195
               196     196
               197     197
               198     198
               199     199

               [200 rows x 7 columns]),
              ((0.2, 25, True, 0.5, 0.4, 0.005, 0),
                    mean_tech  total_lobby     n_allow  mean_prod   emissions    mean_cash  \
               0         3.60     0.000000  461.000000  60.470901  769.931772   604.709009
               1         3.68   157.329279  459.265691  39.790401  347.000000   483.257689
               2         4.08   309.811819  457.493331  44.110397  354.000000   498.811008
               3         4.96   501.222542  456.545899  53.285949  317.000000   562.530653
               4         5.60   810.900125  454.943824  59.919906  307.000000   614.073579
               ..         ...          ...         ...        ...         ...          ...
               195       8.64  3023.279608  291.617091  90.288507  329.000000  1013.563246
               196       8.64  3195.228019  290.617091  94.840037  296.000000  1047.529862
               197       8.64  3115.495301  289.857613  93.754905  262.000000  1068.259130
               198       8.64  2955.264535  288.857613  90.930393  273.000000  1059.328364
               199       8.64  3026.319886  288.233223  91.618501  220.000000  1046.682855

                    period
               0         0
               1         1
               2         2
               3         3
               4         4
               ..      ...
               195     195
               196     196
               197     197
               198     198
               199     199

               [200 rows x 7 columns]),
              ((0.1, 25, True, 0.5, 0.4, 0.005, 3),
                    mean_tech  total_lobby     n_allow   mean_prod    emissions    mean_cash  \
               0         3.60     0.000000  759.000000   82.002703  1265.934996   820.027031
               1         3.64   252.496964  756.000000   70.875800   457.000000   762.656729
               2         4.20   619.593302  755.367570   70.627571   564.000000   749.839356
               3         5.08  1452.048930  752.367570   79.788374   724.000000   761.482120
               4         5.68  2316.258323  749.367570   94.986499   482.000000   898.304173
               ..         ...          ...         ...         ...          ...          ...
               195       8.84  5585.509027  434.963426  128.190909   299.000000  1383.072110
               196       8.84  6154.550590  433.053645  127.723322   532.000000  1345.658314
               197       8.84  5767.844740  432.664982  127.317629   459.000000  1364.591314
               198       8.84  5756.043636  431.803097  127.717106   459.000000  1371.296062
               199       8.84  6228.460338  430.279978  130.033958   404.000000  1371.106290

                    period
               0         0
               1         1
               2         2
               3         3
               4         4
               ..      ...
               195     195
               196     196
               197     197
               198     198
               199     199

               [200 rows x 7 columns]),
              ((0.2, 25, True, 0.5, 0.4, 0.005, 4),
                    mean_tech  total_lobby     n_allow   mean_prod   emissions    mean_cash  \

In [32]:
ex3od = experiment3.get_collector_model()

In [33]:
type(ex3od)

collections.OrderedDict

In [40]:
data3 = []
panel = 0
for key, value in ex3od.items():
    lobby = [key[0] for i in range(len(value.mean_tech))]
    iteration = [key[6] for i in range(len(value))]
    value["coop"] = lobby
    value["Iteration"] = iteration
    value["panel"] = [panel for i in range(len(value))]
    panel += 1
    data3.append(value)

In [41]:
data3

[     mean_tech  total_lobby     n_allow  mean_prod   emissions    mean_cash  \
 0         3.36     0.000000  476.000000  76.909420  794.842189   769.094197
 1         3.40   132.929517  474.000000  55.891386  380.000000   766.324341
 2         4.04   336.125069  472.370522  56.839832  353.000000   766.428589
 3         4.88   640.430751  470.370522  62.688733  380.000000   793.291583
 4         5.24  1155.989407  468.370522  73.251428  469.000000   846.537546
 ..         ...          ...         ...        ...         ...          ...
 195       7.96  3541.636356  301.328122  91.381342  384.000000  1138.936126
 196       7.96  4060.779818  301.033809  93.303859  351.000000  1116.388771
 197       7.96  4597.243646  300.191638  96.007547  327.000000  1119.547376
 198       7.96  4098.477586  299.960917  93.377340  301.000000  1134.492898
 199       7.96  3484.273995  299.690767  95.454140  331.000000  1192.415389

      period  coop  Iteration  panel
 0         0   0.1          0      0
 1         1   0.1          0      0
 2         2   0.1          0      0
 3         3   0.1          0      0
 4         4   0.1          0      0
 ..      ...   ...        ...    ...
 195     195   0.1          0      0
 196     196   0.1          0      0
 197     197   0.1          0      0
 198     198   0.1          0      0
 199     199   0.1          0      0

 [200 rows x 10 columns],
      mean_tech  total_lobby     n_allow   mean_prod    emissions    mean_cash  \
 0         3.68     0.000000  619.000000   70.751024  1032.796356   707.510242
 1         3.76   210.767570  617.471955   55.954392   421.000000   613.749473
 2         4.40   484.212624  614.938314   58.196409   432.000000   631.498891
 3         5.24  1031.086146  613.195109   66.381332   448.000000   659.444031
 4         5.84  1683.545385  612.214556   75.165498   560.000000   735.255045
 ..         ...          ...         ...         ...          ...          ...
 195       8.80  4866.935291  374.300700  109.975788   364.000000  1189.341361
 196       8.80  4564.521264  374.170003  109.501958   407.000000  1199.584348
 197       8.80  4145.978529  373.637371  108.590627   375.000000  1212.062010
 198       8.80  4776.787326  372.637371  104.905015   507.000000  1131.932889
 199       8.80  4120.541743  372.136462  108.671279   395.000000  1195.291696

      period  coop  Iteration  panel
 0         0   0.1          4      1
 1         1   0.1          4      1
 2         2   0.1          4      1
 3         3   0.1          4      1
 4         4   0.1          4      1
 ..      ...   ...        ...    ...
 195     195   0.1          4      1
 196     196   0.1          4      1
 197     197   0.1          4      1
 198     198   0.1          4      1
 199     199   0.1          4      1

 [200 rows x 10 columns],
      mean_tech  total_lobby     n_allow   mean_prod   emissions    mean_cash  \
 0         5.16     0.000000  464.000000  103.559768  774.549668  1035.597683
 1         5.24   150.205397  463.742540   76.776722  352.000000  1016.228325
 2         5.64   473.356532  462.334691   76.774900  393.000000   982.594714
 3         6.44  1057.323714  461.670892   81.941590  360.000000   997.042525
 4         7.04  1941.812298  459.670892   93.043860  422.000000  1054.094167
 ..         ...          ...         ...         ...         ...          ...
 195       9.36  4629.513067  294.478921  108.552113  318.000000  1377.024959
 196       9.36  4393.585547  294.174260  105.517926  285.000000  1364.904338
 197       9.36  4189.098392  293.861847  107.599760  263.000000  1395.263504
 198       9.36  4472.887379  292.861847  112.530129  253.000000  1431.367508
 199       9.36  4397.352104  292.408273  107.608875  310.000000  1420.148530

      period  coop  Iteration  panel
 0         0   0.1          7      2
 1         1   0.1          7      2
 2         2   0.1          7      2
 3         3   0.1          7      2
 4         4   0.1          7      2
 ..      ...   ...        ...    ...
 195     195   0.1          7      2
 196     196   0.1          7      2
 197     197   0.1          7      2
 198     198   0.1          7      2
 199     199   0.1          7      2

 [200 rows x 10 columns],
      mean_tech  total_lobby     n_allow  mean_prod   emissions    mean_cash  \
 0         4.08     0.000000  306.000000  81.849964  511.664544   818.499636
 1         4.16    77.884831  305.158670  44.761275  274.000000   768.907203
 2         4.52   234.391111  304.158670  53.844946  278.000000   813.580100
 3         5.36   375.653207  303.756909  43.813064  285.000000   749.947458
 4         5.84   702.226975  302.756909  53.816805  274.000000   745.174860
 ..         ...          ...         ...        ...         ...          ...
 195       8.28  2438.988016  199.593829  67.750344  182.000000  1000.864410
 196       8.28  2080.177411  199.593829  66.887456  216.000000  1027.237443
 197       8.28  2180.387721  199.593829  70.424439  188.000000  1052.884143
 198       8.28  2158.920968  199.593829  65.063527  154.000000  1010.253345
 199       8.28  2534.939671  199.593829  75.068427  179.000000  1060.581877

      period  coop  Iteration  panel
 0         0   0.1          8      3
 1         1   0.1          8      3
 2         2   0.1          8      3
 3         3   0.1          8      3
 4         4   0.1          8      3
 ..      ...   ...        ...    ...
 195     195   0.1          8      3
 196     196   0.1          8      3
 197     197   0.1          8      3
 198     198   0.1          8      3
 199     199   0.1          8      3

 [200 rows x 10 columns],
      mean_tech  total_lobby     n_allow  mean_prod   emissions    mean_cash  \
 0         3.92     0.000000  335.000000  64.306190  559.085841   643.061896
 1         3.92    81.798059  334.683366  42.694428  277.000000   621.992041
 2         4.28   210.421541  334.308356  40.403029  300.000000   561.058520
 3         4.96   297.558107  334.109352  47.705880  258.000000   624.181220
 4         5.56   432.758718  333.988669  47.809712  240.000000   604.486780
 ..         ...          ...         ...        ...         ...          ...
 195       8.00  1726.088476  199.645711  73.223691  202.000000  1019.656512
 196       8.00  1746.986555  199.645711  69.916566  192.000000   975.346868
 197       8.00  1687.751850  199.645711  68.238776  208.000000   942.024208
 198       8.00  1578.125578  199.645711  72.518288  194.000000   980.258926
 199       8.00  1865.953501  199.645711  74.218951  170.000000   967.159391

      period  coop  Iteration  panel
 0         0   0.2          1      4
 1         1   0.2          1      4
 2         2   0.2          1      4
 3         3   0.2          1      4
 4         4   0.2          1      4
 ..      ...   ...        ...    ...
 195     195   0.2          1      4
 196     196   0.2          1      4
 197     197   0.2          1      4
 198     198   0.2          1      4
 199     199   0.2          1      4

 [200 rows x 10 columns],
      mean_tech  total_lobby     n_allow   mean_prod   emissions    mean_cash  \
 0         3.88     0.000000  549.000000   78.382196  916.593853   783.821960
 1         3.92   204.260603  547.000000   65.537609  415.000000   762.708413
 2         4.44   447.796473  545.505428   63.854996  450.000000   767.638072
 3         5.20  1142.571481  543.505428   73.407241  312.000000   765.429313
 4         5.72  1846.379006  542.492815   76.028962  485.000000   792.619535
 ..         ...          ...         ...         ...         ...          ...
 195       8.40  3983.850656  334.279888  101.594147  311.000000  1169.327591
 196       8.40  4065.853249  333.279888  101.115530  330.000000  1166.304334
 197       8.40  4563.307848  332.859552  102.298582  411.000000  1149.888467
 198       8.40  5115.345031  331.859552  104.195004  330.000000  1151.476623
 199       8.40  4533.270675  331.289089  101.938667  407.000000  1168.680593

      period  coop  Iteration  panel
 0         0   0.1          6      5
 1         1   0.1          6      5
 2         2   0.1          6      5
 3         3   0.1          6      5
 4         4   0.1          6      5
 ..      ...   ...        ...    ...
 195     195   0.1          6      5
 196     196   0.1          6      5
 197     197   0.1          6      5
 198     198   0.1          6      5
 199     199   0.1          6      5

 [200 rows x 10 columns],
      mean_tech  total_lobby     n_allow  mean_prod   emissions    mean_cash  \
 0         4.52     0.000000  555.000000  81.339163  925.359146   813.391634
 1         4.52   218.566236  554.007781  58.472023  447.000000   676.823168
 2         4.92   679.546429  552.234839  69.667288  403.000000   730.983896
 3         5.80  1332.567447  550.234839  75.833185  509.000000   789.937817
 4         6.60  2122.473573  548.733851  82.693412  436.000000   837.442383
 ..         ...          ...         ...        ...         ...          ...
 195       8.84  4028.584437  332.631778  96.531800  318.000000  1083.426159
 196       8.84  4136.532760  332.435421  93.931723  402.000000  1064.109132
 197       8.84  4129.905597  331.435421  94.755859  292.000000  1060.750660
 198       8.84  4012.724900  330.643329  98.424270  273.000000  1106.236302
 199       8.84  4831.761634  329.733374  96.231829  455.000000  1049.197812

      period  coop  Iteration  panel
 0         0   0.1          2      6
 1         1   0.1          2      6
 2         2   0.1          2      6
 3         3   0.1          2      6
 4         4   0.1          2      6
 ..      ...   ...        ...    ...
 195     195   0.1          2      6
 196     196   0.1          2      6
 197     197   0.1          2      6
 198     198   0.1          2      6
 199     199   0.1          2      6

 [200 rows x 10 columns],
      mean_tech  total_lobby     n_allow  mean_prod  emissions   mean_cash  \
 0         3.56     0.000000  383.000000  60.169513  639.87176  601.695133
 1         3.60   106.902981  382.670567  39.089832  311.00000  520.882364
 2         4.08   256.070548  381.987423  45.968401  304.00000  549.711705
 3         4.92   388.090605  380.987423  47.603979  344.00000  571.676246
 4         5.36   649.220365  380.696253  55.965239  252.00000  607.868419
 ..         ...          ...         ...        ...        ...         ...
 195       7.88  2587.055413  239.071790  74.279110  214.00000  885.401895
 196       7.88  2276.102004  238.938267  75.539100  283.00000  923.735976
 197       7.88  2468.094236  238.160635  74.576425  245.00000  901.687788
 198       7.88  2731.086896  237.780647  77.366794  248.00000  899.885334
 199       7.88  2630.001769  236.780647  79.224222  297.00000  947.796277

      period  coop  Iteration  panel
 0         0   0.2          3      7
 1         1   0.2          3      7
 2         2   0.2          3      7
 3         3   0.2          3      7
 4         4   0.2          3      7
 ..      ...   ...        ...    ...
 195     195   0.2          3      7
 196     196   0.2          3      7
 197     197   0.2          3      7
 198     198   0.2          3      7
 199     199   0.2          3      7

 [200 rows x 10 columns],
      mean_tech  total_lobby     n_allow   mean_prod   emissions    mean_cash  \
 0         3.72     0.000000  593.000000   76.758548  989.021932   767.585482
 1         3.76   131.047508  591.000000   51.368959  512.000000   670.991748
 2         4.04   363.132924  589.000000   53.558588  422.000000   631.603281
 3         4.88   843.818793  587.211989   63.432365  474.000000   664.067450
 4         5.60  1406.122162  586.134590   68.512300  449.000000   712.689631
 ..         ...          ...         ...         ...         ...          ...
 195       9.00  4895.575561  358.280192  112.000103  368.000000  1268.935975
 196       9.00  4933.746641  357.678718  110.255382  492.000000  1263.373476
 197       9.00  4671.884611  356.678718  107.324178  406.000000  1245.110120
 198       9.00  4797.516016  355.678718  109.405039  316.000000  1250.129353
 199       9.00  4114.487447  355.187379  102.757420  390.000000  1220.374269

      period  coop  Iteration  panel
 0         0   0.1          5      8
 1         1   0.1          5      8
 2         2   0.1          5      8
 3         3   0.1          5      8
 4         4   0.1          5      8
 ..      ...   ...        ...    ...
 195     195   0.1          5      8
 196     196   0.1          5      8
 197     197   0.1          5      8
 198     198   0.1          5      8
 199     199   0.1          5      8

 [200 rows x 10 columns],
      mean_tech  total_lobby     n_allow   mean_prod    emissions    mean_cash  \
 0         3.92     0.000000  665.000000   77.254615  1109.896896   772.546150
 1         4.04   245.859647  664.133236   69.760440   411.000000   756.642757
 2         4.52   683.516135  663.754124   62.965052   560.000000   685.480600
 3         5.48  1151.614943  661.398803   65.043760   566.000000   674.467442
 4         6.04  2490.822651  658.398803   88.273314   509.000000   790.898504
 ..         ...          ...         ...         ...          ...          ...
 195       8.96  5336.000570  379.969641  110.904906   557.000000  1202.044795
 196       8.96  4785.717995  379.678853  113.014767   431.000000  1238.349228
 197       8.96  5132.813999  378.678853  107.172950   330.000000  1157.263597
 198       8.96  5015.748489  377.835666  110.274993   572.000000  1179.546504
 199       8.96  4612.749279  376.835666  108.408743   392.000000  1185.226022

      period  coop  Iteration  panel
 0         0   0.1          1      9
 1         1   0.1          1      9
 2         2   0.1          1      9
 3         3   0.1          1      9
 4         4   0.1          1      9
 ..      ...   ...        ...    ...
 195     195   0.1          1      9
 196     196   0.1          1      9
 197     197   0.1          1      9
 198     198   0.1          1      9
 199     199   0.1          1      9

 [200 rows x 10 columns],
      mean_tech  total_lobby     n_allow   mean_prod   emissions    mean_cash  \
 0         4.60     0.000000  533.000000   88.521421  889.082349   885.214211
 1         4.80   220.404830  531.000000   71.298813  386.000000   842.835786
 2         5.40   565.441563  529.199177   73.064029  450.000000   869.729764
 3         6.36  1069.333093  527.398678   83.116850  379.000000   949.648663
 4         6.80  2385.844042  525.398678   95.384610  412.000000   980.079704
 ..         ...          ...         ...         ...         ...          ...
 195       9.08  4438.112132  327.058372  110.108694  221.000000  1306.138758
 196       9.08  4645.787421  326.103239   99.594405  354.000000  1214.780864
 197       9.08  4010.068693  325.103239   99.182917  315.000000  1206.880131
 198       9.08  4997.828383  324.129069  104.959792  287.000000  1194.462087
 199       9.08  4627.562801  323.873325  111.859690  331.000000  1308.742519

      period  coop  Iteration  panel
 0         0   0.1          9     10
 1         1   0.1          9     10
 2         2   0.1          9     10
 3         3   0.1          9     10
 4         4   0.1          9     10
 ..      ...   ...        ...    ...
 195     195   0.1          9     10
 196     196   0.1          9     10
 197     197   0.1          9     10
 198     198   0.1          9     10
 199     199   0.1          9     10

 [200 rows x 10 columns],
      mean_tech  total_lobby     n_allow  mean_prod   emissions    mean_cash  \
 0         3.60     0.000000  461.000000  60.470901  769.931772   604.709009
 1         3.68   157.329279  459.265691  39.790401  347.000000   483.257689
 2         4.08   309.811819  457.493331  44.110397  354.000000   498.811008
 3         4.96   501.222542  456.545899  53.285949  317.000000   562.530653
 4         5.60   810.900125  454.943824  59.919906  307.000000   614.073579
 ..         ...          ...         ...        ...         ...          ...
 195       8.64  3023.279608  291.617091  90.288507  329.000000  1013.563246
 196       8.64  3195.228019  290.617091  94.840037  296.000000  1047.529862
 197       8.64  3115.495301  289.857613  93.754905  262.000000  1068.259130
 198       8.64  2955.264535  288.857613  90.930393  273.000000  1059.328364
 199       8.64  3026.319886  288.233223  91.618501  220.000000  1046.682855

      period  coop  Iteration  panel
 0         0   0.2          0     11
 1         1   0.2          0     11
 2         2   0.2          0     11
 3         3   0.2          0     11
 4         4   0.2          0     11
 ..      ...   ...        ...    ...
 195     195   0.2          0     11
 196     196   0.2          0     11
 197     197   0.2          0     11
 198     198   0.2          0     11
 199     199   0.2          0     11

 [200 rows x 10 columns],
      mean_tech  total_lobby     n_allow   mean_prod    emissions    mean_cash  \
 0         3.60     0.000000  759.000000   82.002703  1265.934996   820.027031
 1         3.64   252.496964  756.000000   70.875800   457.000000   762.656729
 2         4.20   619.593302  755.367570   70.627571   564.000000   749.839356
 3         5.08  1452.048930  752.367570   79.788374   724.000000   761.482120
 4         5.68  2316.258323  749.367570   94.986499   482.000000   898.304173
 ..         ...          ...         ...         ...          ...          ...
 195       8.84  5585.509027  434.963426  128.190909   299.000000  1383.072110
 196       8.84  6154.550590  433.053645  127.723322   532.000000  1345.658314
 197       8.84  5767.844740  432.664982  127.317629   459.000000  1364.591314
 198       8.84  5756.043636  431.803097  127.717106   459.000000  1371.296062
 199       8.84  6228.460338  430.279978  130.033958   404.000000  1371.106290

      period  coop  Iteration  panel
 0         0   0.1          3     12
 1         1   0.1          3     12
 2         2   0.1          3     12
 3         3   0.1          3     12
 4         4   0.1          3     12
 ..      ...   ...        ...    ...
 195     195   0.1          3     12
 196     196   0.1          3     12
 197     197   0.1          3     12
 198     198   0.1          3     12
 199     199   0.1          3     12

 [200 rows x 10 columns],
      mean_tech  total_lobby     n_allow   mean_prod   emissions    mean_cash  \
 0         3.96     0.000000  596.000000   70.453124  993.735755   704.531240
 1         4.08   235.209586  594.000000   60.645254  374.000000   640.317382
 2         4.56   490.395324  592.000000   57.243202  446.000000   607.954228
 3         5.48   959.137349  590.301514   67.595093  412.000000   653.804213
 4         6.12  1526.756179  590.029538   76.380490  439.000000   718.238115
 ..         ...          ...         ...         ...         ...          ...
 195       9.36  4859.250590  359.320216  102.865536  402.000000  1078.559134
 196       9.36  4140.458024  358.415164  100.921756  356.000000  1097.515538
 197       9.36  3573.979064  358.123571   99.731509  359.000000  1108.640661
 198       9.36  3228.157508  357.758681   97.299415  363.000000  1093.807654
 199       9.36  3519.604776  357.327796   97.338774  390.000000  1059.439518

      period  coop  Iteration  panel
 0         0   0.2          4     13
 1         1   0.2          4     13
 2         2   0.2          4     13
 3         3   0.2          4     13
 4         4   0.2          4     13
 ..      ...   ...        ...    ...
 195     195   0.2          4     13
 196     196   0.2          4     13
 197     197   0.2          4     13
 198     198   0.2          4     13
 199     199   0.2          4     13

 [200 rows x 10 columns],
      mean_tech  total_lobby     n_allow   mean_prod    emissions    mean_cash  \
 0         2.92     0.000000  622.000000   60.578677  1037.521607   605.786773
 1         2.92   192.542268  619.726181   48.927997   439.000000   566.315234

In [42]:
df3 = pd.concat(data3)

In [43]:
df3

,mean_tech,total_lobby,n_allow,mean_prod,emissions,mean_cash,period,coop,Iteration,panel
0,3.36,0.000000,476.000000,76.909420,794.842189,769.094197,0,0.1,0,0
1,3.40,132.929517,474.000000,55.891386,380.000000,766.324341,1,0.1,0,0
2,4.04,336.125069,472.370522,56.839832,353.000000,766.428589,2,0.1,0,0
3,4.88,640.430751,470.370522,62.688733,380.000000,793.291583,3,0.1,0,0
4,5.24,1155.989407,468.370522,73.251428,469.000000,846.537546,4,0.1,0,0
...,...,...,...,...,...,...,...,...,...,...
195,9.44,53.273416,324.439583,94.872845,418.000000,959.241401,195,0.8,8,79
196,9.44,52.529924,323.439583,92.442428,355.000000,947.102919,196,0.8,8,79
197,9.44,52.198018,322.726456,94.267176,366.000000,953.456793,197,0.8,8,79
198,9.44,53.252212,322.561274,92.182433,509.000000,944.775595,198,0.8,8,79
199,9.44,49.633782,321.833695,94.558951,387.000000,977.644791,199,0.8,8,79

In [44]:
df3.to_csv("out_data/CoopExperiment.csv")

Experiment 4: Market Size and Company Size
        Will directly compare two kinds of markets - markets with many small agents vs markets with few large agents

In [45]:
fixed_params4 = {
  "am": True,
  "cap_size": .4,
  "dec": .005,
  "lobby": .33
}
variable_params4 = {
  "N": [10, 100],
  "mSize": [.9, .1]
}

In [46]:
experiment4 = BatchRunnerMP(Environment,
    nr_processes= None,
    variable_parameters = variable_params4, 
    fixed_parameters = fixed_params4,
    iterations = 10,
    max_steps = 200)

BatchRunner MP will use 16 processors.

In [47]:
experiment4.run_all()

40it [01:32,  2.31s/it]

(None,
 None,
 OrderedDict([((10, 0.1, True, 0.4, 0.005, 0.33, 4),
                    mean_tech  total_lobby  n_allow  mean_prod   emissions    mean_cash  \
               0          5.6     0.000000     84.0  76.070382  140.215006   760.703818
               1          5.6     7.424667     84.0  51.342932   61.000000   852.291357
               2          6.1    12.141191     84.0  46.048421   71.000000   801.978587
               3          6.7    24.196475     84.0  43.725567   87.000000   721.262082
               4          6.9    44.047907     84.0  52.053274  104.000000   748.424303
               ..         ...          ...      ...        ...         ...          ...
               195        9.1   419.336425     84.0  81.291673   67.000000  1028.695670
               196        9.1   502.744477     84.0  79.836354   70.000000  1019.335231
               197        9.1   406.131237     84.0  77.987158   60.000000  1043.969914
               198        9.1   343.441293     84.0  74.942230   75.000000  1007.562525
               199        9.1   333.757690     84.0  76.977628  122.000000  1010.142445

                    period
               0         0
               1         1
               2         2
               3         3
               4         4
               ..      ...
               195     195
               196     196
               197     197
               198     198
               199     199

               [200 rows x 7 columns]),
              ((10, 0.1, True, 0.4, 0.005, 0.33, 2),
                    mean_tech  total_lobby  n_allow  mean_prod   emissions   mean_cash  \
               0          3.2     0.000000     66.0  35.073213  110.644617  350.732129
               1          3.4     8.375098     66.0  20.502140   46.000000  345.431819
               2          4.1    11.195867     66.0  18.580916   61.000000  327.271992
               3          5.0    11.429084     66.0  21.108828   64.000000  331.336378
               4          5.3    21.267225     66.0  27.556569   67.000000  367.311293
               ..         ...          ...      ...        ...         ...         ...
               195        7.4   125.087531     66.0  48.272467   67.000000  609.003740
               196        7.4   111.030981     66.0  38.216760   75.000000  525.684067
               197        7.4   110.448796     66.0  45.099185   51.000000  550.769755
               198        7.4   127.931741     66.0  39.946125   65.000000  500.326790
               199        7.4   119.950183     66.0  46.253745   48.000000  566.035049

                    period
               0         0
               1         1
               2         2
               3         3
               4         4
               ..      ...
               195     195
               196     196
               197     197
               198     198
               199     199

               [200 rows x 7 columns]),
              ((10, 0.1, True, 0.4, 0.005, 0.33, 0),
                    mean_tech  total_lobby  n_allow  mean_prod  emissions   mean_cash  period
               0          3.8     0.000000     58.0  35.429391  97.260592  354.293905       0
               1          3.8     5.830925     58.0  26.698579  33.000000  367.965094       1
               2          4.1     9.246083     58.0  25.021232  74.000000  363.293180       2
               3          4.5     7.424015     58.0  17.184412  48.000000  312.603782       3
               4          4.7    13.941788     58.0  30.950860  67.000000  357.731789       4
               ..         ...          ...      ...        ...        ...         ...     ...
               195        6.3    69.644227     58.0  39.426127  39.000000  468.534905     195
               196        6.3    53.848071     58.0  38.864470  50.000000  504.472459     196
               197        6.3    52.987509     58.0  39.137740  33.000000  506.554642     197
               198        6.3    33.886826     58.0  38.835673  49.000000  534.874187     198
               199        6.3    33.909063     58.0  38.500000  72.000000  508.540136     199

               [200 rows x 7 columns]),
              ((10, 0.1, True, 0.4, 0.005, 0.33, 5),
                    mean_tech  total_lobby  n_allow  mean_prod   emissions    mean_cash  \
               0          3.9     0.000000    114.0  53.753216  190.924138   537.532165
               1          3.9    16.199515    114.0  37.833201  100.000000   544.604761
               2          4.5    15.635271    114.0  31.234576  117.000000   527.146181
               3          5.3    27.113674    114.0  31.553886   91.000000   471.529142
               4          5.8    41.852119    114.0  41.198407  115.000000   495.983489
               ..         ...          ...      ...        ...         ...          ...
               195        9.0   787.608265    114.0  84.559609   95.000000   934.759830
               196        9.0   714.305935    114.0  89.500000  212.000000   977.550361
               197        9.0   836.499243    114.0  89.500000  214.000000   951.633219
               198        9.0   684.657368    114.0  89.500000   67.000000  1013.547935
               199        9.0   687.134227    114.0  85.393801  102.000000   982.375878

                    period
               0         0
               1         1
               2         2
               3         3
               4         4
               ..      ...
               195     195
               196     196
               197     197
               198     198
               199     199

               [200 rows x 7 columns]),
              ((10, 0.1, True, 0.4, 0.005, 0.33, 1),
                    mean_tech  total_lobby  n_allow  mean_prod  emissions   mean_cash  period
               0          3.6     0.000000    149.0  55.658921  249.10897  556.589208       0
               1          3.6    17.821986    149.0  42.782194  123.00000  553.371970       1
               2          4.3    27.113079    149.0  39.788600  127.00000  540.431493       2
               3          5.2    47.682451    149.0  44.014912   94.00000  528.093900       3
               4          5.6    99.332614    149.0  57.102154   79.00000  557.090629       4
               ..         ...          ...      ...        ...        ...         ...     ...
               195        8.7   688.212822    149.0  85.071742  111.00000  810.280693     195
               196        8.7   670.907562    149.0  85.939863  170.00000  806.432312     196
               197        8.7   745.641930    149.0  86.700000   89.00000  815.883588     197
               198        8.7   685.730866    149.0  86.700000  132.00000  828.148370     198
               199        8.7   744.197877    149.0  86.700000  237.00000  800.082912     199

               [200 rows x 7 columns]),
              ((10, 0.9, True, 0.4, 0.005, 0.33, 6),
                    mean_tech  total_lobby     n_allow   mean_prod   emissions    mean_cash  \
               0          5.2     0.000000  213.000000  129.759914  356.308665  1297.599139
               1          5.3    32.623266  212.692870   98.825980  173.000000  1371.216115
               2          5.9    57.735894  211.692870   86.118655  202.000000  1279.884092
               3          6.9    75.500062  211.420411   89.261938  225.000000  1260.154054
               4          7.5   161.912438  210.788476  137.772954  137.000000  1534.640462
               ..         ...          ...         ...         ...         ...          ...
               195       11.3  1796.508002  199.376391  178.299642  179.000000  2051.835052
               196       11.3  1887.789085  199.376391  164.284839  284.000000  1886.821563
               197       11.3  1484.505468  199.376391  151.911002  210.000000  1797.729075
               198       11.3  1753.979320  199.376391  157.273175  188.000000  1688.147702
               199       11.3  1599.761561  199.376391  152.105781  209.000000  1690.151997

                    period
               0         0
               1         1
               2         2
               3         3
               4         4
               ..      ...
               195     195
               196     196
               197     197
               198     198
               199     199

               [200 rows x 7 columns]),
              ((10, 0.9, True, 0.4, 0.005, 0.33, 3),
                    mean_tech  total_lobby     n_allow   mean_prod   emissions    mean_cash  \
               0          4.7     0.000000  221.000000  114.715067  369.859572  1147.150668
               1          4.7    29.321910  220.248500   84.314377  154.000000  1110.106879
               2          5.2    48.382772  219.921289   82.562505  128.000000  1083.949582
               3          6.1    75.085329  219.729625   85.131791  211.000000  1016.244499
               4          6.5   107.368721  219.464846  106.173303  140.000000  1203.705051
               ..         ...          ...         ...         ...         ...          ...
               195       10.1  1444.262397  199.565331  152.670743  181.000000  1580.155589
               196       10.1  1443.772065  199.565331  155.700000  236.000000  1654.170565
               197       10.1  1221.057023  199.565331  155.700000  227.000000  1715.539714
               198       10.1  1333.559509  199.565331  155.700000  225.000000  1690.226546
               199       10.1  1483.382750  199.565331  154.246418  177.000000  1622.990630

                    period
               0         0
               1         1
               2         2
               3         3
               4         4
               ..      ...
               195     195
               196     196
               197     197
               198     198
               199     199

               [200 rows x 7 columns]),
              ((10, 0.9, True, 0.4, 0.005, 0.33, 5),
                    mean_tech  total_lobby     n_allow   mean_prod   emissions    mean_cash  \
               0          3.0     0.000000  316.000000   99.051437  528.128861   990.514369
               1          3.1    34.843040  315.000000   65.171277  262.000000   879.894978
               2          3.6    60.399992  314.000000   82.465604  228.000000  1033.899197
               3          4.5   103.986582  313.000000   79.909479  336.000000   963.812463
               4          5.2   134.487428  312.358768   71.993576  234.000000   865.788102
               ..         ...          ...         ...         ...         ...          ...
               195       11.0  1843.878170  199.104846  176.787784  174.000000  1943.977093
               196       11.0  1827.779118  199.104846  158.574344  293.000000  1832.607122
               197       11.0  1444.021032  199.104846  125.965387  219.000000  1553.518627
               198       11.0  1810.853084  199.104846  173.043135  323.000000  1760.352945
               199       11.0  1538.021878  199.104846  178.109309  127.000000  2031.048057

                    period
               0         0
               1         1
               2         2
               3         3
               4         4
               ..      ...
               195     195
               196     196
               197     197
               198     198
               199     199

               [200 rows x 7 columns]),
              ((10, 0.9, True, 0.4, 0.005, 0.33, 0),
                    mean_tech  total_lobby     n_allow   mean_prod   emissions    mean_cash  \
               0          5.4     0.000000  239.000000  111.992298  399.292176  1119.922977
               1          5.7    36.363638  238.000000   87.731147  178.000000  1101.157620
               2          5.9    88.461577  237.000000   95.755934  167.000000  1087.938892
               3          6.8   157.127028  236.487661  106.906094  201.000000  1197.382592
               4          7.6   229.628118  235.641776  105.884769  222.000000  1205.486390
               ..         ...          ...         ...         ...         ...          ...
               195       10.6  1234.974944  199.499083  154.600000  339.000000  1701.117335
               196       10.6  1606.639572  199.499083  147.389126  362.000000  1507.810536
               197       10.6  1666.830622  199.499083  142.076914  214.000000  1462.936739
               198       10.6  1842.382063  199.499083  134.567248  205.000000  1327.427310
               199       10.6  1876.927741  199.499083  149.245026  122.000000  1448.013211

                    period
               0         0
               1         1
               2         2
               3         3
               4         4
               ..      ...
               195     195
               196     196
               197     197
               198     198
               199     199

               [200 rows x 7 columns]),
              ((10, 0.1, True, 0.4, 0.005, 0.33, 3),
                    mean_tech  total_lobby     n_allow   mean_prod   emissions   mean_cash  \
               0          3.3     0.000000  224.000000   55.110120  374.569211  551.101195
               1          3.6    21.685449  223.000000   36.334805  191.000000  465.073542
               2          4.1    50.841995  222.000000   47.007288  174.000000  506.520375
               3          4.7    79.646319  221.282353   53.287827  177.000000  536.046318
               4          5.5    70.308380  220.282353   56.282905  141.000000  621.839256
               ..         ...          ...         ...         ...         ...         ...
               195        8.9   956.508507  199.820787  102.500000  130.000000  951.768132
               196        8.9   959.209071  199.820787  102.500000  109.000000  913.968174
               197        8.9   915.702253  199.820787  102.500000  209.000000  930.325124
               198        8.9   888.871043  199.820787  102.500000  165.000000  951.250985
               199        8.9   791.042436  199.820787  102.500000  112.000000  982.401791

                    period
               0         0
               1         1
               2         2
               3         3
               4         4
               ..      ...
               195     195
               196     196
               197     197
               198     198
               199     199

               [200 rows x 7 columns]),
              ((10, 0.9, True, 0.4, 0.005, 0.33, 4),
                    mean_tech  total_lobby     n_allow   mean_prod   emissions    mean_cash  \
               0          2.8     0.000000  280.000000   74.057884  467.638533   740.578839
               1          2.9    26.792582  279.000000   55.533915  228.000000   749.087800
               2          3.1    61.153633  278.563180   67.170210  216.000000   810.191477
               3          4.1   104.595800  278.423065   64.325450  182.000000   789.978991
               4          4.8   129.886753  277.423065   73.979432  297.000000   839.011304
               ..         ...          ...         ...         ...         ...          ...
               195       10.1  1645.106044  199.948119  142.511246  149.000000  1417.165609
               196       10.1  1926.360424  199.948119  144.700000  326.000000  1405.427041
               197       10.1  1518.925781  199.948119  144.700000  148.000000  1505.931501
               198       10.1  1815.650189  199.948119  144.700000  212.000000  1435.832528
               199       10.1  2175.971151  199.948119  144.700000  178.000000  1380.766140

                    period
               0         0
               1         1
               2         2
               3         3
               4         4
               ..      ...
               195     195
               196     196
               197     197
               198     198
               199     199

               [200 rows x 7 columns]),
              ((10, 0.9, True, 0.4, 0.005, 0.33, 9),
                    mean_tech  total_lobby     n_allow   mean_prod   emissions    mean_cash  \
               0          3.3     0.000000  308.000000  100.729171  513.642336  1007.291707
               1          3.3    52.070758  307.248773   88.408128  225.000000  1034.958749
               2          3.9    69.537867  306.579563   53.966848  280.000000   789.148928
               3          4.8   111.864672  305.775594   94.162219  165.000000  1009.575727
               4          5.5   165.822780  305.318896   96.158569  252.000000  1049.132415
               ..         ...          ...         ...         ...         ...          ...
               195       10.6  2205.497407  199.729591  162.093388  176.000000  1791.675962
               196       10.6  2100.856858  199.729591  163.729505  226.000000  1790.695182
               197       10.6  1876.486244  199.729591  160.939373  283.000000  1809.628807
               198       10.6  1814.579217  199.729591  155.483546  123.000000  1735.856122
               199       10.6  1983.454169  199.729591  173.318406  231.000000  1846.562686

                    period
               0         0
               1         1
               2         2
               3         3
               4         4
               ..      ...
               195     195
               196     196
               197     197
               198     198
               199     199

               [200 rows x 7 columns]),
              ((10, 0.9, True, 0.4, 0.005, 0.33, 1),
                    mean_tech  total_lobby     n_allow   mean_prod   emissions    mean_cash  \
               0          5.0     0.000000  281.000000   79.184662  468.923421   791.846620
               1          5.2    51.775423  280.838190   59.869312  181.000000   592.633586
               2          5.6    91.458080  280.111682   75.055952  173.000000   710.231361
               3          6.3   137.355629  279.899355   76.088636  236.000000   739.756851
               4          7.0   207.981002  279.617524   90.900000  139.000000   816.830049
               ..         ...          ...         ...         ...         ...          ...
               195        9.8   965.427056  199.583632  120.100000   87.000000  1148.682667
               196        9.8   907.969444  199.583632  120.100000  207.000000  1150.671690
               197        9.8   657.661459  199.583632  120.100000  132.000000  1208.573503
               198        9.8   676.717436  199.583632  120.100000  170.000000  1171.921627
               199        9.8   952.763427  199.583632  120.100000  127.000000  1041.586636

                    period
               0         0
               1         1
               2         2
               3         3
               4         4
               ..      ...
               195     195
               196     196
               197     197
               198     198
               199     199

               [200 rows x 7 columns]),
              ((10, 0.9, True, 0.4, 0.005, 0.33, 8),
                    mean_tech  total_lobby     n_allow   mean_prod   emissions    mean_cash  \
               0          3.0     0.000000  336.000000   91.869905  560.948673   918.699052
               1          3.0    34.566410  335.840876   56.523663  273.000000   736.667216
               2          3.5    63.879153  335.143507   61.525683  295.000000   705.611910
               3          4.1   101.335091  334.291095   82.163889  217.000000   862.069965
               4          4.8   200.926039  333.730298   98.630271  210.000000   964.353286
               ..         ...          ...         ...         ...         ...          ...
               195       10.3  2195.571177  199.231691  172.800000  320.000000  1898.617306
               196       10.3  2020.543054  199.231691  161.486666  240.000000  1837.855332

In [48]:
ex4od = experiment4.get_collector_model()

In [73]:
data4 = []
panel2 = 0
for key, value in ex4od.items():
    N = [key[0] for i in range(len(value.mean_tech))]
    mSize = [key[1] for i in range(len(value))]
    iteration = [key[6] for i in range(len(value))]
    value["N"] = N
    value["mSize"] = mSize
    value["Iteration"] = iteration
    value["panel"] = [panel2 for i in range(len(value))]
    panel2 += 1
    data4.append(value)

In [78]:
df4 = pd.concat(data4)

In [79]:
df4.to_csv("out_data/Market_Size_Experiment.csv")