In [3]:
from mesa.batchrunner import BatchRunner, BatchRunnerMP
import pandas as pd
from model import Environment
from os import cpu_count

Market Size and Distribution Experiment

In [4]:
#Experiment 1 Variables 
fixed_params = {
  "N": 25,
  "cap_size": .35,
  "mSize":  .5,
  "lobby": .33,
  "dec": .005  
}
variable_params = {
    "am": [False, True]
}

In [5]:
experiment1 = BatchRunnerMP(Environment,
    nr_processes= None,
    variable_parameters = variable_params, 
    fixed_parameters = fixed_params,
    iterations = 5,
    max_steps = 200)

BatchRunner MP will use 16 processors.

In [6]:
experiment1.run_all()

10it [00:21,  2.18s/it]

(None,
 None,
 OrderedDict([((False, 25, 0.35, 0.5, 0.33, 0.005, 4),
                    mean_tech  total_lobby     n_allow  mean_prod   emissions     mean_cash  \
               0         3.44     0.000000  587.000000  65.719621  904.346687  6.571962e+02
               1         3.56   180.542201  585.989334  54.023337  420.000000  1.063630e+03
               2         4.12   277.458324  583.989334  57.953726  387.000000  1.518737e+03
               3         5.04   400.277744  581.989334  57.607616  584.000000  1.948040e+03
               4         5.68   456.478444  580.883066  61.024895  440.000000  2.418407e+03
               ..         ...          ...         ...        ...         ...           ...
               496       8.76   107.231683  199.597988  70.234067  126.000000 -1.675333e+29
               497       8.76   123.260648  199.597988  75.455282  274.000000 -1.675333e+29
               498       8.76   120.980959  199.597988  75.213511  195.000000 -1.675333e+29
               499       8.76   118.275149  199.597988  69.374510  194.000000 -1.675333e+29
               500       8.76   132.668078  199.597988  68.994192  222.000000 -1.675333e+29

                    period
               0         0
               1         1
               2         2
               3         3
               4         4
               ..      ...
               496     496
               497     497
               498     498
               499     499
               500     500

               [501 rows x 7 columns]),
              ((False, 25, 0.35, 0.5, 0.33, 0.005, 1),
                    mean_tech  total_lobby     n_allow  mean_prod   emissions      mean_cash  \
               0         4.68     0.000000  574.000000  88.691813  884.482117     886.918128
               1         4.72   266.156838  573.401268  78.114552  449.000000    1452.903053
               2         5.24   480.135224  571.401268  69.146287  446.000000    1938.186501
               3         6.24   578.205229  569.401268  69.243934  429.000000    2443.728104
               4         6.76   705.876498  567.940242  76.409928  414.000000    3012.951618
               ..         ...          ...         ...        ...         ...            ...
               496       9.52   148.428454  199.252765  75.627383  194.000000  361774.394227
               497       9.52   144.076444  199.252765  71.732035  174.000000  362308.643568
               498       9.52   161.523230  199.252765  75.655142  138.000000  362874.911609
               499       9.52   147.272059  199.252765  71.361700  216.000000  363420.747268
               500       9.52   154.090053  199.252765  75.886687  212.000000  363985.825621

                    period
               0         0
               1         1
               2         2
               3         3
               4         4
               ..      ...
               496     496
               497     497
               498     498
               499     499
               500     500

               [501 rows x 7 columns]),
              ((False, 25, 0.35, 0.5, 0.33, 0.005, 3),
                    mean_tech  total_lobby     n_allow  mean_prod  emissions      mean_cash  \
               0         3.72     0.000000  442.000000  72.254495   680.3854     722.544947
               1         3.72   133.947928  441.731929  56.500155   333.0000    1153.437894
               2         4.32   200.152357  439.731929  53.516512   315.0000    1555.948676
               3         5.20   313.876035  438.151285  56.854644   286.0000    1963.562923
               4         5.80   343.422393  436.151285  56.221153   234.0000    2383.321331
               ..         ...          ...         ...        ...        ...            ...
               496       9.12   152.961316  199.432902  60.819569   250.0000  299281.565737
               497       9.12   174.781721  199.432902  61.260217   205.0000  299714.437534
               498       9.12   178.650041  199.432902  57.929306   134.0000  300134.210515
               499       9.12   223.769417  199.432902  63.904733   171.0000  300570.502557
               500       9.12   170.586870  199.432902  61.398108   141.0000  301059.053121

                    period
               0         0
               1         1
               2         2
               3         3
               4         4
               ..      ...
               496     496
               497     497
               498     498
               499     499
               500     500

               [501 rows x 7 columns]),
              ((False, 25, 0.35, 0.5, 0.33, 0.005, 0),
                    mean_tech  total_lobby     n_allow  mean_prod   emissions      mean_cash  \
               0         3.48     0.000000  527.000000  71.080764  811.705627     710.807644
               1         3.48   192.280261  525.000000  61.250969  398.000000    1164.895103
               2         4.12   309.039944  523.863611  54.459945  478.000000    1564.581763
               3         5.12   387.245313  522.488045  59.194837  379.000000    1997.899328
               4         5.64   476.296576  521.012724  66.709374  315.000000    2491.006776
               ..         ...          ...         ...        ...         ...            ...
               496       9.16   167.359920  199.378330  68.810918  134.000000  325719.086863
               497       9.16   182.936068  199.378330  70.033649  299.000000  326229.048690
               498       9.16   167.406248  199.378330  67.519216  207.000000  326742.803818
               499       9.16   167.721971  199.378330  61.070094  179.000000  327186.353454
               500       9.16   129.464196  199.378330  65.323018  324.000000  327696.281773

                    period
               0         0
               1         1
               2         2
               3         3
               4         4
               ..      ...
               496     496
               497     497
               498     498
               499     499
               500     500

               [501 rows x 7 columns]),
              ((False, 25, 0.35, 0.5, 0.33, 0.005, 2),
                    mean_tech  total_lobby     n_allow  mean_prod   emissions      mean_cash  \
               0         4.48     0.000000  624.000000  77.820798  960.314664     778.207985
               1         4.56   251.250194  621.000000  62.048112  415.000000    1231.236145
               2         5.12   348.875214  618.000000  58.154879  313.000000    1686.770596
               3         6.08   440.021390  616.440005  66.638297  288.000000    2202.909124
               4         6.52   608.084885  613.440045  70.964784  409.000000    2731.201356
               ..         ...          ...         ...        ...         ...            ...
               496       9.44   149.236114  199.864352  62.856507  141.000000  362022.549808
               497       9.44   189.611539  199.864352  64.573896  239.000000  362467.598895
               498       9.44   231.387188  199.864352  69.439149  263.000000  362981.319810
               499       9.44   194.310269  199.864352  67.534039  253.000000  363526.243153
               500       9.44   216.176130  199.864352  68.995960  219.000000  364017.218069

                    period
               0         0
               1         1
               2         2
               3         3
               4         4
               ..      ...
               496     496
               497     497
               498     498
               499     499
               500     500

               [501 rows x 7 columns]),
              ((True, 25, 0.35, 0.5, 0.33, 0.005, 2),
                    mean_tech  total_lobby     n_allow  mean_prod   emissions    mean_cash  \
               0         4.24     0.000000  512.000000  73.426542  789.007994   734.265422
               1         4.24   175.742944  510.928355  57.832910  405.000000   682.233485
               2         4.88   308.210937  509.351352  55.748064  380.000000   644.369222
               3         5.72   511.486441  508.313989  65.509045  365.000000   683.502516
               4         6.32   755.418952  506.313989  75.198942  408.000000   750.472330
               ..         ...          ...         ...        ...         ...          ...
               496       9.56   731.682303  199.300011  79.280145  161.000000  1077.306882
               497       9.56   770.731619  199.300011  70.260904  223.000000  1011.418909
               498       9.56   701.681574  199.300011  68.281058  200.000000   982.223957
               499       9.56   602.548523  199.300011  69.199392  165.000000   992.405157
               500       9.56   586.334203  199.300011  70.883457  205.000000   986.985263

                    period
               0         0
               1         1
               2         2
               3         3
               4         4
               ..      ...
               496     496
               497     497
               498     498
               499     499
               500     500

               [501 rows x 7 columns]),
              ((True, 25, 0.35, 0.5, 0.33, 0.005, 3),
                    mean_tech  total_lobby     n_allow  mean_prod   emissions    mean_cash  \
               0         4.36     0.000000  562.000000  80.787921  866.002553   807.879212
               1         4.36   222.415278  560.887351  70.770790  451.000000   783.948493
               2         4.92   413.511261  558.887351  66.966888  407.000000   737.694019
               3         5.84   642.332538  556.887351  77.318562  423.000000   794.905123
               4         6.52   788.301442  554.887351  75.851683  372.000000   779.526002
               ..         ...          ...         ...        ...         ...          ...
               496       9.88   810.631743  199.717947  71.759920  204.000000  1068.605931
               497       9.88   959.562101  199.717947  77.504375  182.000000  1094.914004
               498       9.88   759.877789  199.717947  64.111699  209.000000  1041.342789
               499       9.88   725.200211  199.717947  63.343288  189.000000   976.288002
               500       9.88   704.013408  199.717947  75.613090  168.000000  1071.228644

                    period
               0         0
               1         1
               2         2
               3         3
               4         4
               ..      ...
               496     496
               497     497
               498     498
               499     499
               500     500

               [501 rows x 7 columns]),
              ((True, 25, 0.35, 0.5, 0.33, 0.005, 0),
                    mean_tech  total_lobby     n_allow  mean_prod   emissions    mean_cash  \
               0         4.16     0.000000  613.000000  88.274758  943.486901   882.747583
               1         4.20   217.048227  612.279823  65.179572  464.000000   793.215407
               2         4.72   387.976152  610.710118  65.783954  399.000000   751.340580
               3         5.56   553.919302  609.006846  76.566009  460.000000   819.095413
               4         6.20   748.505785  607.478530  85.824519  479.000000   871.901941
               ..         ...          ...         ...        ...         ...          ...
               496      10.00   331.156118  199.406315  74.633052  213.000000  1238.758453
               497      10.00   359.762063  199.406315  81.984381  191.000000  1279.524688
               498      10.00   314.203540  199.406315  65.587246  184.000000  1188.292773
               499      10.00   287.502041  199.406315  80.643782  234.000000  1258.368497
               500      10.00   273.166468  199.406315  73.987136  232.000000  1227.144495

                    period
               0         0
               1         1
               2         2
               3         3
               4         4
               ..      ...
               496     496
               497     497
               498     498
               499     499
               500     500

               [501 rows x 7 columns]),
              ((True, 25, 0.35, 0.5, 0.33, 0.005, 4),
                    mean_tech  total_lobby     n_allow  mean_prod    emissions    mean_cash  \
               0         3.40     0.000000  719.000000  74.332013  1106.867742   743.320125
               1         3.48   212.258106  716.896701  61.377144   457.000000   689.429737
               2         3.84   469.819399  713.896701  67.406662   547.000000   689.883436
               3         4.80   617.721359  713.283834  68.301596   503.000000   712.016446
               4         5.44   970.443496  711.924930  80.686992   518.000000   734.740814
               ..         ...          ...         ...        ...          ...          ...
               496       9.68   341.776140  199.929801  74.370858   180.000000  1094.444322
               497       9.68   245.093925  199.929801  68.223359   192.000000  1098.997173
               498       9.68   289.502770  199.929801  78.651197   206.000000  1122.773000
               499       9.68   295.946214  199.929801  80.438093   180.000000  1179.307576
               500       9.68   269.443330  199.929801  73.574004   218.000000  1162.981021

                    period
               0         0
               1         1
               2         2
               3         3
               4         4
               ..      ...
               496     496
               497     497
               498     498
               499     499
               500     500

               [501 rows x 7 columns]),
              ((True, 25, 0.35, 0.5, 0.33, 0.005, 1),
                    mean_tech  total_lobby     n_allow   mean_prod    emissions    mean_cash  \
               0         3.56     0.000000  874.000000   78.053809  1345.205141   780.538087
               1         3.60   342.379176  871.942226   69.775077   599.000000   697.299901
               2         4.20   611.275671  869.533208   67.595093   702.000000   650.866282
               3         5.16   844.004862  865.533208   77.451307   516.000000   725.730992
               4         5.68  1379.472675  863.724023   87.172222   627.000000   745.965975
               ..         ...          ...         ...         ...          ...          ...
               496       9.76   719.549804  233.167130   97.165670   342.000000  1303.388172
               497       9.76   738.772472  232.241409  101.175117   301.000000  1375.005007
               498       9.76   702.903551  232.109387  103.609552   357.000000  1453.461082
               499       9.76   710.249541  231.109387   96.773316   486.000000  1405.120468
               500       9.76   823.126395  230.109387   98.073906   204.000000  1367.525761

                    period
               0         0
               1         1
               2         2
               3         3
               4         4
               ..      ...
               496     496
               497     497
               498     498
               499     499
               500     500

               [501 rows x 7 columns])]),
 OrderedDict([((False, 25, 0.35, 0.5, 0.33, 0.005, 4),
               Empty DataFrame
               Columns: []
               Index: []),
              ((False, 25, 0.35, 0.5, 0.33, 0.005, 1),
               Empty DataFrame
               Columns: []
               Index: []),
              ((False, 25, 0.35, 0.5, 0.33, 0.005, 3),
               Empty DataFrame
               Columns: []
               Index: []),
              ((False, 25, 0.35, 0.5, 0.33, 0.005, 0),
               Empty DataFrame
               Columns: []
               Index: []),
              ((False, 25, 0.35, 0.5, 0.33, 0.005, 2),
               Empty DataFrame
               Columns: []
               Index: []),
              ((True, 25, 0.35, 0.5, 0.33, 0.005, 2),
               Empty DataFrame
               Columns: []
               Index: []),
              ((True, 25, 0.35, 0.5, 0.33, 0.005, 3),
               Empty DataFrame
               Columns: []
               Index: []),
              ((True, 25, 0.35, 0.5, 0.33, 0.005, 0),
               Empty DataFrame
               Columns: []
               Index: []),
              ((True, 25, 0.35, 0.5, 0.33, 0.005, 4),
               Empty DataFrame
               Columns: []
               Index: []),
              ((True, 25, 0.35, 0.5, 0.33, 0.005, 1),
               Empty DataFrame
               Columns: []
               Index: [])]))

In [7]:
od = experiment1.get_collector_model()

In [9]:
print(od)

OrderedDict([((False, 25, 0.35, 0.5, 0.33, 0.005, 4),      mean_tech  total_lobby     n_allow  mean_prod   emissions     mean_cash  \
0         3.44     0.000000  587.000000  65.719621  904.346687  6.571962e+02
1         3.56   180.542201  585.989334  54.023337  420.000000  1.063630e+03
2         4.12   277.458324  583.989334  57.953726  387.000000  1.518737e+03
3         5.04   400.277744  581.989334  57.607616  584.000000  1.948040e+03
4         5.68   456.478444  580.883066  61.024895  440.000000  2.418407e+03
..         ...          ...         ...        ...         ...           ...
496       8.76   107.231683  199.597988  70.234067  126.000000 -1.675333e+29
497       8.76   123.260648  199.597988  75.455282  274.000000 -1.675333e+29
498       8.76   120.980959  199.597988  75.213511  195.000000 -1.675333e+29
499       8.76   118.275149  199.597988  69.374510  194.000000 -1.675333e+29
500       8.76   132.668078  199.597988  68.994192  222.000000 -1.675333e+29

     period
0         0
1         1
2         2
3         3
4         4
..      ...
496     496
497     497
498     498
499     499
500     500

[501 rows x 7 columns]), ((False, 25, 0.35, 0.5, 0.33, 0.005, 1),      mean_tech  total_lobby     n_allow  mean_prod   emissions      mean_cash  \
0         4.68     0.000000  574.000000  88.691813  884.482117     886.918128
1         4.72   266.156838  573.401268  78.114552  449.000000    1452.903053
2         5.24   480.135224  571.401268  69.146287  446.000000    1938.186501
3         6.24   578.205229  569.401268  69.243934  429.000000    2443.728104
4         6.76   705.876498  567.940242  76.409928  414.000000    3012.951618
..         ...          ...         ...        ...         ...            ...
496       9.52   148.428454  199.252765  75.627383  194.000000  361774.394227
497       9.52   144.076444  199.252765  71.732035  174.000000  362308.643568
498       9.52   161.523230  199.252765  75.655142  138.000000  362874.911609
499       9.52   147.272059  199.252765  71.361700  216.000000  363420.747268
500       9.52   154.090053  199.252765  75.886687  212.000000  363985.825621

     period
0         0
1         1
2         2
3         3
4         4
..      ...
496     496
497     497
498     498
499     499
500     500

[501 rows x 7 columns]), ((False, 25, 0.35, 0.5, 0.33, 0.005, 3),      mean_tech  total_lobby     n_allow  mean_prod  emissions      mean_cash  \
0         3.72     0.000000  442.000000  72.254495   680.3854     722.544947
1         3.72   133.947928  441.731929  56.500155   333.0000    1153.437894
2         4.32   200.152357  439.731929  53.516512   315.0000    1555.948676
3         5.20   313.876035  438.151285  56.854644   286.0000    1963.562923
4         5.80   343.422393  436.151285  56.221153   234.0000    2383.321331
..         ...          ...         ...        ...        ...            ...
496       9.12   152.961316  199.432902  60.819569   250.0000  299281.565737
497       9.12   174.781721  199.432902  61.260217   205.0000  299714.437534
498       9.12   178.650041  199.432902  57.929306   134.0000  300134.210515
499       9.12   223.769417  199.432902  63.904733   171.0000  300570.502557
500       9.12   170.586870  199.432902  61.398108   141.0000  301059.053121

     period
0         0
1         1
2         2
3         3
4         4
..      ...
496     496
497     497
498     498
499     499
500     500

[501 rows x 7 columns]), ((False, 25, 0.35, 0.5, 0.33, 0.005, 0),      mean_tech  total_lobby     n_allow  mean_prod   emissions      mean_cash  \
0         3.48     0.000000  527.000000  71.080764  811.705627     710.807644
1         3.48   192.280261  525.000000  61.250969  398.000000    1164.895103
2         4.12   309.039944  523.863611  54.459945  478.000000    1564.581763
3         5.12   387.245313  522.488045  59.194837  379.000000    1997.899328
4         5.64   476.296576  521.012724  66.709374  315.000000    2491.006776
..         ...          ...         ...        ...         ...            ...
496       9.16   167.359920  199.378330  68.810918  134.000000  325719.086863
497       9.16   182.936068  199.378330  70.033649  299.000000  326229.048690
498       9.16   167.406248  199.378330  67.519216  207.000000  326742.803818
499       9.16   167.721971  199.378330  61.070094  179.000000  327186.353454
500       9.16   129.464196  199.378330  65.323018  324.000000  327696.281773

     period
0         0
1         1
2         2
3         3
4         4
..      ...
496     496
497     497
498     498
499     499
500     500

[501 rows x 7 columns]), ((False, 25, 0.35, 0.5, 0.33, 0.005, 2),      mean_tech  total_lobby     n_allow  mean_prod   emissions      mean_cash  \
0         4.48     0.000000  624.000000  77.820798  960.314664     778.207985
1         4.56   251.250194  621.000000  62.048112  415.000000    1231.236145
2         5.12   348.875214  618.000000  58.154879  313.000000    1686.770596
3         6.08   440.021390  616.440005  66.638297  288.000000    2202.909124
4         6.52   608.084885  613.440045  70.964784  409.000000    2731.201356
..         ...          ...         ...        ...         ...            ...
496       9.44   149.236114  199.864352  62.856507  141.000000  362022.549808
497       9.44   189.611539  199.864352  64.573896  239.000000  362467.598895
498       9.44   231.387188  199.864352  69.439149  263.000000  362981.319810
499       9.44   194.310269  199.864352  67.534039  253.000000  363526.243153
500       9.44   216.176130  199.864352  68.995960  219.000000  364017.218069

     period
0         0
1         1
2         2
3         3
4         4
..      ...
496     496
497     497
498     498
499     499
500     500

[501 rows x 7 columns]), ((True, 25, 0.35, 0.5, 0.33, 0.005, 2),      mean_tech  total_lobby     n_allow  mean_prod   emissions    mean_cash  \
0         4.24     0.000000  512.000000  73.426542  789.007994   734.265422
1         4.24   175.742944  510.928355  57.832910  405.000000   682.233485
2         4.88   308.210937  509.351352  55.748064  380.000000   644.369222
3         5.72   511.486441  508.313989  65.509045  365.000000   683.502516
4         6.32   755.418952  506.313989  75.198942  408.000000   750.472330
..         ...          ...         ...        ...         ...          ...
496       9.56   731.682303  199.300011  79.280145  161.000000  1077.306882
497       9.56   770.731619  199.300011  70.260904  223.000000  1011.418909
498       9.56   701.681574  199.300011  68.281058  200.000000   982.223957
499       9.56   602.548523  199.300011  69.199392  165.000000   992.405157
500       9.56   586.334203  199.300011  70.883457  205.000000   986.985263

     period
0         0
1         1
2         2
3         3
4         4
..      ...
496     496
497     497
498     498
499     499
500     500

[501 rows x 7 columns]), ((True, 25, 0.35, 0.5, 0.33, 0.005, 3),      mean_tech  total_lobby     n_allow  mean_prod   emissions    mean_cash  \
0         4.36     0.000000  562.000000  80.787921  866.002553   807.879212
1         4.36   222.415278  560.887351  70.770790  451.000000   783.948493
2         4.92   413.511261  558.887351  66.966888  407.000000   737.694019
3         5.84   642.332538  556.887351  77.318562  423.000000   794.905123
4         6.52   788.301442  554.887351  75.851683  372.000000   779.526002
..         ...          ...         ...        ...         ...          ...
496       9.88   810.631743  199.717947  71.759920  204.000000  1068.605931
497       9.88   959.562101  199.717947  77.504375  182.000000  1094.914004
498       9.88   759.877789  199.717947  64.111699  209.000000  1041.342789
499       9.88   725.200211  199.717947  63.343288  189.000000   976.288002
500       9.88   704.013408  199.717947  75.613090  168.000000  1071.228644

     period
0         0
1         1
2         2
3         3
4         4
..      ...
496     496
497     497
498     498
499     499
500     500

[501 rows x 7 columns]), ((True, 25, 0.35, 0.5, 0.33, 0.005, 0),      mean_tech  total_lobby     n_allow  mean_prod   emissions    mean_cash  \
0         4.16     0.000000  613.000000  88.274758  943.486901   882.747583
1         4.20   217.048227  612.279823  65.179572  464.000000   793.215407
2         4.72   387.976152  610.710118  65.783954  399.000000   751.340580
3         5.56   553.919302  609.006846  76.566009  460.000000   819.095413
4         6.20   748.505785  607.478530  85.824519  479.000000   871.901941
..         ...          ...         ...        ...         ...          ...
496      10.00   331.156118  199.406315  74.633052  213.000000  1238.758453
497      10.00   359.762063  199.406315  81.984381  191.000000  1279.524688
498      10.00   314.203540  199.406315  65.587246  184.000000  1188.292773
499      10.00   287.502041  199.406315  80.643782  234.000000  1258.368497
500      10.00   273.166468  199.406315  73.987136  232.000000  1227.144495

     period
0         0
1         1
2         2
3         3
4         4
..      ...
496     496
497     497
498     498
499     499
500     500

[501 rows x 7 columns]), ((True, 25, 0.35, 0.5, 0.33, 0.005, 4),      mean_tech  total_lobby     n_allow  mean_prod    emissions    mean_cash  \
0         3.40     0.000000  719.000000  74.332013  1106.867742   743.320125
1         3.48   212.258106  716.896701  61.377144   457.000000   689.429737
2         3.84   469.819399  713.896701  67.406662   547.000000   689.883436
3         4.80   617.721359  713.283834  68.301596   503.000000   712.016446
4         5.44   970.443496  711.924930  80.686992   518.000000   734.740814
..         ...          ...         ...        ...          ...          ...
496       9.68   341.776140  199.929801  74.370858   180.000000  1094.444322
497       9.68   245.093925  199.929801  68.223359   192.000000  1098.997173
498       9.68   289.502770  199.929801  78.651197   206.000000  1122.773000
499       9.68   295.946214  199.929801  80.438093   180.000000  1179.307576
500       9.68   269.443330  199.929801  73.574004   218.000000  1162.981021

     period
0         0
1         1
2         2
3         3
4         4
..      ...
496     496
497     497
498     498
499     499
500     500

[501 rows x 7 columns]), ((True, 25, 0.35, 0.5, 0.33, 0.005, 1),      mean_tech  total_lobby     n_allow   mean_prod    emissions    mean_cash  \
0         3.56     0.000000  874.000000   78.053809  1345.205141   780.538087
1         3.60   342.379176  871.942226   69.775077   599.000000   697.299901
2         4.20   611.275671  869.533208   67.595093   702.000000   650.866282
3         5.16   844.004862  865.533208   77.451307   516.000000   725.730992
4         5.68  1379.472675  863.724023   87.172222   627.000000   745.965975
..         ...          ...         ...         ...          ...          ...
496       9.76   719.549804  233.167130   97.165670   342.000000  1303.388172
497       9.76   738.772472  232.241409  101.175117   301.000000  1375.005007
498       9.76   702.903551  232.109387  103.609552   357.000000  1453.461082
499       9.76   710.249541  231.109387   96.773316   486.000000  1405.120468
500       9.76   823.126395  230.109387   98.073906   204.000000  1367.525761

     period
0         0
1         1
2         2
3         3
4         4
..      ...
496     496
497     497
498     498
499     499
500     500

[501 rows x 7 columns])])

In [17]:
type(df.keys())

odict_keys

In [18]:
df.key()

odict_values([     mean_tech  total_lobby     n_allow  mean_prod   emissions      mean_cash  \
0         3.92     0.000000  604.000000  76.938300  930.678582     769.382997
1         3.96   244.318789  602.480122  62.975423  411.000000    1222.890098
2         4.48   373.812399  600.423338  58.972563  410.000000    1665.782848
3         5.44   402.649709  597.423338  60.288731  376.000000    2128.112465
4         5.96   511.052032  596.435041  68.023877  392.000000    2643.989789
..         ...          ...         ...        ...         ...            ...
496       9.72   149.380301  199.023066  69.281409  203.000000  371189.105003
497       9.72   120.619979  199.023066  68.866728  182.000000  371720.914894
498       9.72   103.569335  199.023066  69.363202  161.000000  372267.672880
499       9.72   115.300330  199.023066  70.248793  221.000000  372768.084223
500       9.72   100.324501  199.023066  68.057900  227.000000  373293.245407

     period
0         0
1         1
2         2
3         3
4         4
..      ...
496     496
497     497
498     498
499     499
500     500

[501 rows x 7 columns],      mean_tech  total_lobby     n_allow  mean_prod   emissions      mean_cash  \
0         3.72     0.000000  368.000000  62.188415  567.380595     621.884148
1         3.80   116.023834  367.000000  46.943972  310.000000     972.077645
2         4.44   153.375685  366.000000  43.533574  261.000000    1318.961316
3         5.40   217.226403  365.516743  46.794756  214.000000    1672.509960
4         5.80   288.890287  364.516743  54.875045  283.000000    2091.805049
..         ...          ...         ...        ...         ...            ...
496       8.96   326.050325  199.774156  59.135976  127.000000  256120.655747
497       8.96   263.701150  199.774156  54.051648  213.000000  256515.263375
498       8.96   249.630926  199.774156  59.356289  124.000000  256974.342332
499       8.96   220.052397  199.774156  53.897287  196.000000  257370.335001
500       8.96   210.374079  199.774156  54.304875  258.000000  257777.063227

     period
0         0
1         1
2         2
3         3
4         4
..      ...
496     496
497     497
498     498
499     499
500     500

[501 rows x 7 columns],      mean_tech  total_lobby     n_allow  mean_prod   emissions      mean_cash  \
0         4.24     0.000000  590.000000  76.395840  909.053284     763.958398
1         4.32   223.751374  588.000000  61.513439  406.000000    1219.123878
2         5.00   325.836114  587.666090  56.596923  346.000000    1653.292832
3         5.96   413.592915  585.666090  61.428552  318.000000    2125.341510
4         6.40   642.161496  583.962070  71.030215  410.000000    2640.780969
..         ...          ...         ...        ...         ...            ...
496       9.40   196.199078  199.115403  63.810532  257.000000  344480.802649
497       9.40   169.882342  199.115403  62.134051  174.000000  344951.035938
498       9.40   167.112234  199.115403  61.119935  145.000000  345398.443356
499       9.40   171.790023  199.115403  66.840347  183.000000  345907.866781
500       9.40   166.907664  199.115403  68.889299  164.000000  346434.343646

     period
0         0
1         1
2         2
3         3
4         4
..      ...
496     496
497     497
498     498
499     499
500     500

[501 rows x 7 columns],      mean_tech  total_lobby     n_allow  mean_prod    emissions  \
0         4.40     0.000000  669.000000  69.901059  1029.781946
1         4.40   220.734734  667.833331  56.962331   399.000000
2         4.76   366.166597  665.236119  57.436940   337.000000
3         5.52   592.266346  664.904352  66.308231   351.000000
4         6.04   756.432193  661.904352  73.648798   371.000000
..         ...          ...         ...        ...          ...
496       9.32   197.666219  199.626097  75.785480   361.000000
497       9.32   179.832417  199.626097  72.263762   208.000000
498       9.32   198.548922  199.626097  79.601213   156.000000
499       9.32   205.178640  199.626097  76.553105   175.000000
500       9.32   184.553708  199.626097  74.698239   174.000000

         mean_cash  period
0       699.010594       0
1      1152.858223       1
2      1596.181076       2
3      2100.878660       3
4      2672.440273       4
..             ...     ...
496  355910.002076     496
497  356464.935682     497
498  357071.030337     498
499  357656.987676     499
500  358238.050231     500

[501 rows x 7 columns],      mean_tech  total_lobby     n_allow  mean_prod   emissions      mean_cash  \
0         3.92     0.000000  434.000000  74.298046  669.073968     742.980459
1         4.04   143.265431  432.866990  54.804291  349.000000    1142.828182
2         4.76   230.190162  431.718886  58.039902  287.000000    1580.689216
3         5.64   337.164501  429.955957  62.107572  265.000000    2033.600049
4         6.20   393.115813  427.955957  65.651983  245.000000    2520.513129
..         ...          ...         ...        ...         ...            ...
496       9.24    98.379179  199.445474  60.620435  204.000000  298845.598871
497       9.24    94.042432  199.445474  65.756016  397.000000  299361.602841
498       9.24   122.138817  199.445474  73.875802  203.000000  299906.012577
499       9.24   105.965069  199.445474  66.337801  200.000000  300427.940805
500       9.24    82.150286  199.445474  61.914988  149.000000  300919.818046

     period
0         0
1         1
2         2
3         3
4         4
..      ...
496     496
497     497
498     498
499     499
500     500

[501 rows x 7 columns],      mean_tech  total_lobby     n_allow  mean_prod   emissions    mean_cash  \
0         3.40     0.000000  509.000000  65.114336  783.243418   651.143363
1         3.40   146.130041  508.683527  45.650044  349.000000   573.301563
2         3.76   264.167122  506.892489  46.122767  425.000000   543.822024
3         4.56   421.030920  506.023013  56.360882  340.000000   605.044207
4         5.24   537.718156  504.332793  59.615493  485.000000   633.557646
..         ...          ...         ...        ...         ...          ...
496       9.24   497.564428  199.724150  78.006586  186.000000  1087.398076
497       9.24   478.773813  199.724150  77.518444  216.000000  1115.924476
498       9.24   520.093038  199.724150  75.517780  222.000000  1066.815947
499       9.24   468.313322  199.724150  66.332327  260.000000   999.820762
500       9.24   390.204755  199.724150  73.709269  274.000000  1065.736962

     period
0         0
1         1
2         2
3         3
4         4
..      ...
496     496
497     497
498     498
499     499
500     500

[501 rows x 7 columns],      mean_tech  total_lobby     n_allow  mean_prod   emissions    mean_cash  \
0         3.68     0.000000  491.000000  74.042913  756.052728   740.429126
1         3.72   173.942781  490.048983  57.890629  361.000000   672.689442
2         4.12   262.430685  488.048983  57.496653  442.000000   656.109420
3         4.88   358.127395  487.128948  64.508013  435.000000   702.758061
4         5.36   424.939374  486.182295  67.481768  297.000000   722.697303
..         ...          ...         ...        ...         ...          ...
496       8.64   122.975014  199.014423  66.567042  171.000000   975.102487
497       8.64   132.060272  199.014423  75.379716  185.000000  1055.360930
498       8.64   179.076172  199.014423  76.010501  176.000000  1037.159492
499       8.64   183.033622  199.014423  76.077439  194.000000  1056.960564
500       8.64   196.921810  199.014423  72.261710  167.000000  1036.423200

     period
0         0
1         1
2         2
3         3
4         4
..      ...
496     496
497     497
498     498
499     499
500     500

[501 rows x 7 columns],      mean_tech  total_lobby     n_allow  mean_prod   emissions    mean_cash  \
0         4.00     0.000000  573.000000  78.574379  882.073538   785.743788
1         4.04   187.690502  571.000000  53.148581  491.000000   681.310020
2         4.56   332.687572  569.000000  54.438728  487.000000   641.681958
3         5.36   504.256888  567.000000  64.560039  494.000000   696.549005
4         5.84   866.360309  566.684411  79.974364  426.000000   784.309934
..         ...          ...         ...        ...         ...          ...
496       9.64   371.628271  199.889541  76.293845  214.000000  1198.759290
497       9.64   393.905031  199.889541  77.059674  229.000000  1181.225428
498       9.64   384.293426  199.889541  74.126684  151.000000  1131.307474
499       9.64   370.964251  199.889541  77.291696  164.000000  1160.319579
500       9.64   341.888391  199.889541  68.615349  221.000000  1097.701115

     period
0         0
1         1
2         2
3         3
4         4
..      ...
496     496
497     497
498     498
499     499
500     500

[501 rows x 7 columns],      mean_tech  total_lobby     n_allow  mean_prod   emissions    mean_cash  \
0         3.68     0.000000  621.000000  83.881199  956.086062   838.811986
1         3.76   196.200360  618.000000  62.309540  513.000000   776.236745
2         4.24   336.373037  617.620039  63.651823  507.000000   767.881560
3         5.12   472.253506  616.783735  68.616180  576.000000   778.591761
4         5.72   599.496370  615.435255  79.759207  473.000000   846.802316
..         ...          ...         ...        ...         ...          ...
496      10.28   341.646162  199.930658  78.022395  201.000000  1233.391255
497      10.28   326.094141  199.930658  69.089637  200.000000  1173.491584
498      10.28   388.960409  199.930658  82.420413  225.000000  1227.882493
499      10.28   430.105856  199.930658  86.921476  200.000000  1321.004683
500      10.28   402.409275  199.930658  77.881733  196.000000  1296.685127

     period
0         0
1         1
2         2
3         3
4         4
..      ...
496     496
497     497
498     498
499     499
500     500

[501 rows x 7 columns],      mean_tech  total_lobby      n_allow   mean_prod   emissions    mean_cash  \
0         4.00     0.000000  1075.000000   81.209819  1654.10438   812.098190
1         4.08   442.631480  1074.365466   77.645682   565.00000   710.728897
2         4.64   733.213789  1071.009752   76.753316   763.00000   704.885573
3         5.60  1114.734059  1068.384314   79.123369   637.00000   681.990003
4         6.36  1444.183109  1063.384314   94.063028   570.00000   798.431271
..         ...          ...          ...         ...         ...          ...
496       9.88  2897.577476   275.034656  119.515525   526.00000  1591.586167
497       9.88  3121.230448   274.765013  119.299677   634.00000  1539.372863
498       9.88  3110.810119   273.765013  120.230036   506.00000  1547.828241
499       9.88  2949.038917   273.042744  120.701757   446.00000  1578.763382
500       9.88  2899.626852   272.042744  120.398787   469.00000  1580.463040

     period
0         0
1         1
2         2
3         3
4         4
..      ...
496     496
497     497
498     498
499     499
500     500

[501 rows x 7 columns]])

In [12]:
df = []
for key, value in od.items():
    auction = key[0]
    iteration = key[6]
    tdf =

False
4
False
1
False
3
False
0
False
2
True
2
True
3
True
0
True
4
True
1