In [42]:
from mesa.batchrunner import BatchRunner, BatchRunnerMP
import pandas as pd
import numpy as np
from model import Environment
from os import cpu_count

Market Size and Distribution Experiment

In [43]:
#Experiment 1 Variables 
fixed_params = {
  "N": 25,
  "cap_size": .35,
  "mSize":  .5,
  "lobby": .33,
  "dec": .005  
}
variable_params = {
    "am": [False, True]
}

In [48]:
experiment1 = BatchRunnerMP(Environment,
    nr_processes= None,
    variable_parameters = variable_params, 
    fixed_parameters = fixed_params,
    iterations = 10,
    max_steps = 200)

BatchRunner MP will use 16 processors.

In [49]:
experiment1.run_all()

20it [00:08,  2.23it/s]

(None,
 None,
 OrderedDict([((False, 25, 0.35, 0.5, 0.33, 0.005, 4),
                    mean_tech  total_lobby     n_allow  mean_prod   emissions      mean_cash  \
               0         4.20     0.000000  433.000000  79.462024  666.840896     794.620237
               1         4.20   166.036231  431.000000  62.453653  324.000000    1255.710878
               2         5.04   151.048260  429.995546  45.541453  381.000000    1631.344154
               3         6.00   197.390469  428.293014  53.799125  299.000000    2051.499568
               4         6.28   263.862138  426.293014  59.038608  218.000000    2503.978397
               ..         ...          ...         ...        ...         ...            ...
               195       9.52   611.643190  272.604690  95.229859  211.000000  141656.731185
               196       9.52   730.081522  271.604690  96.055837  262.000000  142360.700930
               197       9.52   815.658982  270.604690  94.216248  249.000000  143052.337973
               198       9.52   746.561766  269.604690  90.293065  332.000000  143746.519181
               199       9.52   757.716493  268.893031  80.093663  357.000000  144323.610525

                    period
               0         0
               1         1
               2         2
               3         3
               4         4
               ..      ...
               195     195
               196     196
               197     197
               198     198
               199     199

               [200 rows x 7 columns]),
              ((False, 25, 0.35, 0.5, 0.33, 0.005, 8),
                    mean_tech  total_lobby     n_allow   mean_prod  emissions      mean_cash  \
               0         4.00     0.000000  514.000000   88.975699  791.22955     889.756991
               1         4.00   136.989646  512.000000   58.629679  415.00000    1340.176650
               2         4.48   295.271968  510.347885   67.615412  395.00000    1838.714297
               3         5.48   303.460499  508.942479   66.183748  397.00000    2361.640928
               4         6.04   348.383185  506.942479   68.918557  299.00000    2879.264122
               ..         ...          ...         ...         ...        ...            ...
               195       9.60   728.412681  319.139180  100.065957  636.00000  162359.834039
               196       9.60   830.221752  318.613349  106.544610  289.00000  163147.438576
               197       9.60   902.559932  317.613349  108.768747  496.00000  163952.325701
               198       9.60   936.021682  316.613349  109.939462  303.00000  164780.146531
               199       9.60   978.236683  316.084294  101.825035  476.00000  165515.368784

                    period
               0         0
               1         1
               2         2
               3         3
               4         4
               ..      ...
               195     195
               196     196
               197     197
               198     198
               199     199

               [200 rows x 7 columns]),
              ((False, 25, 0.35, 0.5, 0.33, 0.005, 2),
                    mean_tech  total_lobby     n_allow  mean_prod   emissions      mean_cash  \
               0         5.04     0.000000  387.000000  83.994570  596.844304     839.945704
               1         5.04   129.877499  386.081550  58.603250  307.000000    1282.843909
               2         5.40   224.632215  385.644234  62.141744  248.000000    1766.828358
               3         6.20   344.808447  385.076360  64.722782  343.000000    2249.705735
               4         6.80   450.046026  384.356294  65.488453  251.000000    2730.995313
               ..         ...          ...         ...        ...         ...            ...
               195       9.40   366.221076  246.420403  83.121960  243.000000  131137.129954
               196       9.40   325.175830  245.420484  82.049859  217.000000  131789.947757
               197       9.40   343.276394  244.420484  78.707832  375.000000  132401.239412
               198       9.40   394.495503  243.956021  79.851782  410.000000  132980.623658
               199       9.40   384.110706  243.311426  80.627104  191.000000  133599.430389

                    period
               0         0
               1         1
               2         2
               3         3
               4         4
               ..      ...
               195     195
               196     196
               197     197
               198     198
               199     199

               [200 rows x 7 columns]),
              ((False, 25, 0.35, 0.5, 0.33, 0.005, 5),
                    mean_tech  total_lobby     n_allow  mean_prod   emissions      mean_cash  \
               0         4.12     0.000000  475.000000  71.450483  730.896162     714.504830
               1         4.16   189.628392  474.211078  57.411315  365.000000    1123.857611
               2         4.72   252.343438  472.934069  55.299928  314.000000    1555.128450
               3         5.64   336.968604  472.370775  55.350285  251.000000    1955.512078
               4         6.04   437.076802  471.163719  66.101159  272.000000    2437.814349
               ..         ...          ...         ...        ...         ...            ...
               195       8.96   919.774706  294.436468  87.101431  449.000000  139606.795072
               196       8.96   844.559103  293.436468  87.771401  572.000000  140271.167977
               197       8.96   710.438301  292.436468  87.049377  266.000000  140954.343703
               198       8.96   690.911716  291.841176  81.428283  268.000000  141559.478148
               199       8.96   707.642621  291.736501  80.739245  303.000000  142132.838738

                    period
               0         0
               1         1
               2         2
               3         3
               4         4
               ..      ...
               195     195
               196     196
               197     197
               198     198
               199     199

               [200 rows x 7 columns]),
              ((False, 25, 0.35, 0.5, 0.33, 0.005, 1),
                    mean_tech  total_lobby     n_allow  mean_prod   emissions      mean_cash  \
               0         4.04     0.000000  504.000000  68.747695  775.487796     687.476949
               1         4.16   178.635118  502.107383  51.478333  420.000000    1073.664665
               2         4.72   304.784260  500.724602  50.052258  412.000000    1441.740152
               3         5.64   375.796178  498.724602  54.850513  322.000000    1866.013301
               4         6.20   466.460480  497.023590  61.494018  431.000000    2334.333379
               ..         ...          ...         ...        ...         ...            ...
               195       9.24  1543.175916  311.242422  89.061990  292.000000  143730.626823
               196       9.24  1803.774650  310.242422  94.453157  399.000000  144387.901204
               197       9.24  1694.657014  309.279676  93.936857  305.000000  145099.819442
               198       9.24  1682.747619  309.078175  95.132955  374.000000  145804.469146
               199       9.24  1620.385805  308.898436  96.630563  247.000000  146538.032815

                    period
               0         0
               1         1
               2         2
               3         3
               4         4
               ..      ...
               195     195
               196     196
               197     197
               198     198
               199     199

               [200 rows x 7 columns]),
              ((False, 25, 0.35, 0.5, 0.33, 0.005, 9),
                    mean_tech  total_lobby     n_allow   mean_prod    emissions  \
               0         3.72     0.000000  788.000000   63.260209  1213.623651
               1         3.88   233.166838  785.000000   49.621554   571.000000
               2         4.32   473.899440  782.937732   54.958402   483.000000
               3         5.28   602.493098  782.119043   57.441952   447.000000
               4         5.84   846.517313  779.119043   64.428314   396.000000
               ..         ...          ...         ...         ...          ...
               195       9.32  2594.178187  446.769099  103.920000   302.000000
               196       9.32  2388.211688  446.272173  103.920000   339.000000
               197       9.32  2761.390546  444.272173  103.920000   416.000000
               198       9.32  2960.836826  442.272173  103.920000   451.000000
               199       9.32  2566.710951  441.669759  103.920000   477.000000

                        mean_cash  period
               0       632.602094       0
               1      1011.213597       1
               2      1419.499992       2
               3      1850.495356       3
               4      2327.451966       4
               ..             ...     ...
               195  150321.639141     195
               196  151134.624553     196
               197  151899.527614     197
               198  152662.558488     198
               199  153474.401262     199

               [200 rows x 7 columns]),
              ((False, 25, 0.35, 0.5, 0.33, 0.005, 7),
                    mean_tech  total_lobby     n_allow   mean_prod    emissions  \
               0         3.60     0.000000  754.000000   73.559218  1161.287348
               1         3.60   276.819318  751.000000   60.282919   517.000000
               2         4.32   421.710665  748.000000   56.699287   605.000000
               3         5.32   558.249053  747.451429   61.018935   410.000000
               4         5.88   714.292830  745.823282   69.250015   421.000000
               ..         ...          ...         ...         ...          ...
               195       9.44  2721.408432  439.120690  116.365326   473.000000
               196       9.44  2561.798569  438.052438  117.348183   280.000000
               197       9.44  2914.678240  437.141775  115.370231   490.000000
               198       9.44  2885.136058  435.614435  114.665245   310.000000
               199       9.44  2750.464758  434.575982  116.185119   537.000000

                        mean_cash  period
               0       735.592178       0
               1      1177.163439       1
               2      1605.851975       2
               3      2066.470947       3
               4      2596.853089       4
               ..             ...     ...
               195  171798.742360     195
               196  172701.379375     196
               197  173543.654953     197
               198  174405.003860     198
               199  175282.987782     199

               [200 rows x 7 columns]),
              ((False, 25, 0.35, 0.5, 0.33, 0.005, 3),
                    mean_tech  total_lobby     n_allow  mean_prod   emissions      mean_cash  \
               0         3.44     0.000000  527.000000  61.794675  812.130143     617.946753
               1         3.52   155.550711  525.000000  46.565933  407.000000     968.612014
               2         4.12   246.681296  523.266085  45.034437  348.000000    1312.668662
               3         5.00   301.561245  522.218716  51.420125  484.000000    1718.146465
               4         5.48   461.142396  520.218716  60.445266  346.000000    2177.128203
               ..         ...          ...         ...        ...         ...            ...
               195       9.04  1815.040700  322.584671  89.345634  329.000000  136781.026096
               196       9.04  1850.956959  321.584671  91.121447  447.000000  137447.422213
               197       9.04  1825.412233  320.584671  88.663473  288.000000  138108.432337
               198       9.04  1845.828740  319.584671  90.044173  356.000000  138769.333007
               199       9.04  1901.374026  318.584671  90.105332  366.000000  139439.715092

                    period
               0         0
               1         1
               2         2
               3         3
               4         4
               ..      ...
               195     195
               196     196
               197     197
               198     198
               199     199

               [200 rows x 7 columns]),
              ((False, 25, 0.35, 0.5, 0.33, 0.005, 0),
                    mean_tech  total_lobby     n_allow   mean_prod    emissions  \
               0         3.56     0.000000  875.000000   69.190524  1346.992056
               1         3.56   323.652964  871.000000   62.666555   497.000000
               2         4.12   555.507998  867.000000   62.571540   460.000000
               3         5.08   751.268098  863.000000   71.951492   396.000000
               4         5.68  1244.541644  860.627654   78.845291   671.000000
               ..         ...          ...         ...         ...          ...
               195       9.28  3097.485715  484.763706  109.040000   457.000000
               196       9.28  3011.430328  483.308224  109.040000   362.000000
               197       9.28  2758.510528  481.925807  109.040000   556.000000
               198       9.28  3271.023387  479.925807  109.040000   383.000000
               199       9.28  3456.055589  477.925807  109.040000   427.000000

                        mean_cash  period
               0       691.905243       0
               1      1163.965850       1
               2      1640.599445       2
               3      2205.110484       3
               4      2773.725345       4
               ..             ...     ...
               195  158301.606177     195
               196  159129.669278     196
               197  159977.743100     197
               198  160761.484517     198
               199  161549.089352     199

               [200 rows x 7 columns]),
              ((False, 25, 0.35, 0.5, 0.33, 0.005, 6),
                    mean_tech  total_lobby     n_allow   mean_prod    emissions  \
               0         3.72     0.000000  651.000000   67.146553  1002.765239
               1         3.76   216.525215  648.000000   57.960191   358.000000
               2         4.32   366.796965  645.144902   54.990747   380.000000
               3         5.28   440.479135  644.011311   57.068150   413.000000
               4         5.76   524.006734  641.011311   63.142779   338.000000
               ..         ...          ...         ...         ...          ...
               195       9.20  2578.242129  380.683778  104.057786   231.000000
               196       9.20  2629.892032  379.741682  102.118238   451.000000
               197       9.20  2151.116910  379.054517  101.237313   338.000000
               198       9.20  2474.691827  378.054517  100.312226   406.000000
               199       9.20  2771.358967  377.054517  100.760976   542.000000

                        mean_cash  period
               0       671.465526       0
               1      1119.414058       1
               2      1531.596383       2
               3      1976.328140       3
               4      2475.373764       4
               ..             ...     ...
               195  151475.426614     195
               196  152217.557480     196
               197  153006.084972     197
               198  153709.136558     198
               199  154417.157988     199

               [200 rows x 7 columns]),
              ((True, 25, 0.35, 0.5, 0.33, 0.005, 1),
                    mean_tech  total_lobby     n_allow  mean_prod   emissions    mean_cash  \
               0         4.64     0.000000  331.000000  81.731699  510.050463   817.316993
               1         4.76   107.455034  330.000000  55.283335  241.000000   773.423977
               2         5.20   145.981494  329.262983  47.887665  352.000000   734.370430
               3         6.04   192.518590  328.271360  56.996670  237.000000   755.345216
               4         6.32   313.059586  327.271360  66.031394  303.000000   803.587517
               ..         ...          ...         ...        ...         ...          ...
               195       9.16   744.230234  199.289719  83.022424  165.000000  1142.419211
               196       9.16   647.565854  199.289719  77.390364  184.000000  1125.239526
               197       9.16   626.604532  199.289719  83.711825  151.000000  1158.211821
               198       9.16   487.750897  199.289719  71.981739  244.000000  1117.854182
               199       9.16   414.248415  199.289719  76.754854  194.000000  1122.141676

                    period
               0         0
               1         1
               2         2
               3         3
               4         4
               ..      ...
               195     195
               196     196
               197     197
               198     198
               199     199

               [200 rows x 7 columns]),
              ((True, 25, 0.35, 0.5, 0.33, 0.005, 4),
                    mean_tech  total_lobby     n_allow   mean_prod   emissions    mean_cash  \
               0         4.00     0.000000  538.000000   71.516558  828.552783   715.165576
               1         4.00   209.425912  537.644571   60.568376  349.000000   649.851994
               2         4.56   334.311550  536.028889   56.692514  480.000000   621.218924
               3         5.40   560.644845  534.168167   70.534704  385.000000   678.862549
               4         6.00   720.546887  532.168167   71.764305  446.000000   715.572265
               ..         ...          ...         ...         ...         ...          ...
               195       9.08  1861.531505  329.742791   96.177779  388.000000  1040.770960
               196       9.08  1976.989265  328.896992   99.183690  288.000000  1054.679520
               197       9.08  1898.011361  327.896992  101.723973  337.000000  1118.033469
               198       9.08  1916.310778  327.193144   99.989609  383.000000  1096.797369
               199       9.08  1696.793920  326.787496   92.630206  373.000000  1041.471181

                    period
               0         0
               1         1
               2         2
               3         3
               4         4
               ..      ...
               195     195
               196     196
               197     197
               198     198
               199     199

               [200 rows x 7 columns]),
              ((True, 25, 0.35, 0.5, 0.33, 0.005, 5),
                    mean_tech  total_lobby     n_allow   mean_prod   emissions    mean_cash  \
               0         3.84     0.000000  568.000000   76.304613  873.899372   763.046134
               1         4.00   197.255823  567.302170   59.083931  379.000000   653.890912
               2         4.60   248.890954  565.302170   52.567974  555.000000   615.360359
               3         5.44   389.695123  563.302170   67.774124  436.000000   684.311698
               4         5.84   554.918976  561.302170   76.665523  492.000000   761.733152
               ..         ...          ...         ...         ...         ...          ...
               195       9.72  2330.759196  345.481970  106.712166  310.000000  1168.467132
               196       9.72  2480.410194  345.063675  107.443432  303.000000  1169.745542
               197       9.72  2331.718158  344.063675  113.080533  361.000000  1257.014676
               198       9.72  2322.728552  343.063675  104.647835  356.000000  1193.551121
               199       9.72  1966.346094  342.201738  104.317470  389.000000  1205.947554

                    period
               0         0
               1         1
               2         2
               3         3
               4         4
               ..      ...
               195     195
               196     196
               197     197

In [50]:
od = experiment1.get_collector_model()

In [51]:
print(od)

OrderedDict([((False, 25, 0.35, 0.5, 0.33, 0.005, 4),      mean_tech  total_lobby     n_allow  mean_prod   emissions      mean_cash  \
0         4.20     0.000000  433.000000  79.462024  666.840896     794.620237
1         4.20   166.036231  431.000000  62.453653  324.000000    1255.710878
2         5.04   151.048260  429.995546  45.541453  381.000000    1631.344154
3         6.00   197.390469  428.293014  53.799125  299.000000    2051.499568
4         6.28   263.862138  426.293014  59.038608  218.000000    2503.978397
..         ...          ...         ...        ...         ...            ...
195       9.52   611.643190  272.604690  95.229859  211.000000  141656.731185
196       9.52   730.081522  271.604690  96.055837  262.000000  142360.700930
197       9.52   815.658982  270.604690  94.216248  249.000000  143052.337973
198       9.52   746.561766  269.604690  90.293065  332.000000  143746.519181
199       9.52   757.716493  268.893031  80.093663  357.000000  144323.610525

     period
0         0
1         1
2         2
3         3
4         4
..      ...
195     195
196     196
197     197
198     198
199     199

[200 rows x 7 columns]), ((False, 25, 0.35, 0.5, 0.33, 0.005, 8),      mean_tech  total_lobby     n_allow   mean_prod  emissions      mean_cash  \
0         4.00     0.000000  514.000000   88.975699  791.22955     889.756991
1         4.00   136.989646  512.000000   58.629679  415.00000    1340.176650
2         4.48   295.271968  510.347885   67.615412  395.00000    1838.714297
3         5.48   303.460499  508.942479   66.183748  397.00000    2361.640928
4         6.04   348.383185  506.942479   68.918557  299.00000    2879.264122
..         ...          ...         ...         ...        ...            ...
195       9.60   728.412681  319.139180  100.065957  636.00000  162359.834039
196       9.60   830.221752  318.613349  106.544610  289.00000  163147.438576
197       9.60   902.559932  317.613349  108.768747  496.00000  163952.325701
198       9.60   936.021682  316.613349  109.939462  303.00000  164780.146531
199       9.60   978.236683  316.084294  101.825035  476.00000  165515.368784

     period
0         0
1         1
2         2
3         3
4         4
..      ...
195     195
196     196
197     197
198     198
199     199

[200 rows x 7 columns]), ((False, 25, 0.35, 0.5, 0.33, 0.005, 2),      mean_tech  total_lobby     n_allow  mean_prod   emissions      mean_cash  \
0         5.04     0.000000  387.000000  83.994570  596.844304     839.945704
1         5.04   129.877499  386.081550  58.603250  307.000000    1282.843909
2         5.40   224.632215  385.644234  62.141744  248.000000    1766.828358
3         6.20   344.808447  385.076360  64.722782  343.000000    2249.705735
4         6.80   450.046026  384.356294  65.488453  251.000000    2730.995313
..         ...          ...         ...        ...         ...            ...
195       9.40   366.221076  246.420403  83.121960  243.000000  131137.129954
196       9.40   325.175830  245.420484  82.049859  217.000000  131789.947757
197       9.40   343.276394  244.420484  78.707832  375.000000  132401.239412
198       9.40   394.495503  243.956021  79.851782  410.000000  132980.623658
199       9.40   384.110706  243.311426  80.627104  191.000000  133599.430389

     period
0         0
1         1
2         2
3         3
4         4
..      ...
195     195
196     196
197     197
198     198
199     199

[200 rows x 7 columns]), ((False, 25, 0.35, 0.5, 0.33, 0.005, 5),      mean_tech  total_lobby     n_allow  mean_prod   emissions      mean_cash  \
0         4.12     0.000000  475.000000  71.450483  730.896162     714.504830
1         4.16   189.628392  474.211078  57.411315  365.000000    1123.857611
2         4.72   252.343438  472.934069  55.299928  314.000000    1555.128450
3         5.64   336.968604  472.370775  55.350285  251.000000    1955.512078
4         6.04   437.076802  471.163719  66.101159  272.000000    2437.814349
..         ...          ...         ...        ...         ...            ...
195       8.96   919.774706  294.436468  87.101431  449.000000  139606.795072
196       8.96   844.559103  293.436468  87.771401  572.000000  140271.167977
197       8.96   710.438301  292.436468  87.049377  266.000000  140954.343703
198       8.96   690.911716  291.841176  81.428283  268.000000  141559.478148
199       8.96   707.642621  291.736501  80.739245  303.000000  142132.838738

     period
0         0
1         1
2         2
3         3
4         4
..      ...
195     195
196     196
197     197
198     198
199     199

[200 rows x 7 columns]), ((False, 25, 0.35, 0.5, 0.33, 0.005, 1),      mean_tech  total_lobby     n_allow  mean_prod   emissions      mean_cash  \
0         4.04     0.000000  504.000000  68.747695  775.487796     687.476949
1         4.16   178.635118  502.107383  51.478333  420.000000    1073.664665
2         4.72   304.784260  500.724602  50.052258  412.000000    1441.740152
3         5.64   375.796178  498.724602  54.850513  322.000000    1866.013301
4         6.20   466.460480  497.023590  61.494018  431.000000    2334.333379
..         ...          ...         ...        ...         ...            ...
195       9.24  1543.175916  311.242422  89.061990  292.000000  143730.626823
196       9.24  1803.774650  310.242422  94.453157  399.000000  144387.901204
197       9.24  1694.657014  309.279676  93.936857  305.000000  145099.819442
198       9.24  1682.747619  309.078175  95.132955  374.000000  145804.469146
199       9.24  1620.385805  308.898436  96.630563  247.000000  146538.032815

     period
0         0
1         1
2         2
3         3
4         4
..      ...
195     195
196     196
197     197
198     198
199     199

[200 rows x 7 columns]), ((False, 25, 0.35, 0.5, 0.33, 0.005, 9),      mean_tech  total_lobby     n_allow   mean_prod    emissions  \
0         3.72     0.000000  788.000000   63.260209  1213.623651
1         3.88   233.166838  785.000000   49.621554   571.000000
2         4.32   473.899440  782.937732   54.958402   483.000000
3         5.28   602.493098  782.119043   57.441952   447.000000
4         5.84   846.517313  779.119043   64.428314   396.000000
..         ...          ...         ...         ...          ...
195       9.32  2594.178187  446.769099  103.920000   302.000000
196       9.32  2388.211688  446.272173  103.920000   339.000000
197       9.32  2761.390546  444.272173  103.920000   416.000000
198       9.32  2960.836826  442.272173  103.920000   451.000000
199       9.32  2566.710951  441.669759  103.920000   477.000000

         mean_cash  period
0       632.602094       0
1      1011.213597       1
2      1419.499992       2
3      1850.495356       3
4      2327.451966       4
..             ...     ...
195  150321.639141     195
196  151134.624553     196
197  151899.527614     197
198  152662.558488     198
199  153474.401262     199

[200 rows x 7 columns]), ((False, 25, 0.35, 0.5, 0.33, 0.005, 7),      mean_tech  total_lobby     n_allow   mean_prod    emissions  \
0         3.60     0.000000  754.000000   73.559218  1161.287348
1         3.60   276.819318  751.000000   60.282919   517.000000
2         4.32   421.710665  748.000000   56.699287   605.000000
3         5.32   558.249053  747.451429   61.018935   410.000000
4         5.88   714.292830  745.823282   69.250015   421.000000
..         ...          ...         ...         ...          ...
195       9.44  2721.408432  439.120690  116.365326   473.000000
196       9.44  2561.798569  438.052438  117.348183   280.000000
197       9.44  2914.678240  437.141775  115.370231   490.000000
198       9.44  2885.136058  435.614435  114.665245   310.000000
199       9.44  2750.464758  434.575982  116.185119   537.000000

         mean_cash  period
0       735.592178       0
1      1177.163439       1
2      1605.851975       2
3      2066.470947       3
4      2596.853089       4
..             ...     ...
195  171798.742360     195
196  172701.379375     196
197  173543.654953     197
198  174405.003860     198
199  175282.987782     199

[200 rows x 7 columns]), ((False, 25, 0.35, 0.5, 0.33, 0.005, 3),      mean_tech  total_lobby     n_allow  mean_prod   emissions      mean_cash  \
0         3.44     0.000000  527.000000  61.794675  812.130143     617.946753
1         3.52   155.550711  525.000000  46.565933  407.000000     968.612014
2         4.12   246.681296  523.266085  45.034437  348.000000    1312.668662
3         5.00   301.561245  522.218716  51.420125  484.000000    1718.146465
4         5.48   461.142396  520.218716  60.445266  346.000000    2177.128203
..         ...          ...         ...        ...         ...            ...
195       9.04  1815.040700  322.584671  89.345634  329.000000  136781.026096
196       9.04  1850.956959  321.584671  91.121447  447.000000  137447.422213
197       9.04  1825.412233  320.584671  88.663473  288.000000  138108.432337
198       9.04  1845.828740  319.584671  90.044173  356.000000  138769.333007
199       9.04  1901.374026  318.584671  90.105332  366.000000  139439.715092

     period
0         0
1         1
2         2
3         3
4         4
..      ...
195     195
196     196
197     197
198     198
199     199

[200 rows x 7 columns]), ((False, 25, 0.35, 0.5, 0.33, 0.005, 0),      mean_tech  total_lobby     n_allow   mean_prod    emissions  \
0         3.56     0.000000  875.000000   69.190524  1346.992056
1         3.56   323.652964  871.000000   62.666555   497.000000
2         4.12   555.507998  867.000000   62.571540   460.000000
3         5.08   751.268098  863.000000   71.951492   396.000000
4         5.68  1244.541644  860.627654   78.845291   671.000000
..         ...          ...         ...         ...          ...
195       9.28  3097.485715  484.763706  109.040000   457.000000
196       9.28  3011.430328  483.308224  109.040000   362.000000
197       9.28  2758.510528  481.925807  109.040000   556.000000
198       9.28  3271.023387  479.925807  109.040000   383.000000
199       9.28  3456.055589  477.925807  109.040000   427.000000

         mean_cash  period
0       691.905243       0
1      1163.965850       1
2      1640.599445       2
3      2205.110484       3
4      2773.725345       4
..             ...     ...
195  158301.606177     195
196  159129.669278     196
197  159977.743100     197
198  160761.484517     198
199  161549.089352     199

[200 rows x 7 columns]), ((False, 25, 0.35, 0.5, 0.33, 0.005, 6),      mean_tech  total_lobby     n_allow   mean_prod    emissions  \
0         3.72     0.000000  651.000000   67.146553  1002.765239
1         3.76   216.525215  648.000000   57.960191   358.000000
2         4.32   366.796965  645.144902   54.990747   380.000000
3         5.28   440.479135  644.011311   57.068150   413.000000
4         5.76   524.006734  641.011311   63.142779   338.000000
..         ...          ...         ...         ...          ...
195       9.20  2578.242129  380.683778  104.057786   231.000000
196       9.20  2629.892032  379.741682  102.118238   451.000000
197       9.20  2151.116910  379.054517  101.237313   338.000000
198       9.20  2474.691827  378.054517  100.312226   406.000000
199       9.20  2771.358967  377.054517  100.760976   542.000000

         mean_cash  period
0       671.465526       0
1      1119.414058       1
2      1531.596383       2
3      1976.328140       3
4      2475.373764       4
..             ...     ...
195  151475.426614     195
196  152217.557480     196
197  153006.084972     197
198  153709.136558     198
199  154417.157988     199

[200 rows x 7 columns]), ((True, 25, 0.35, 0.5, 0.33, 0.005, 1),      mean_tech  total_lobby     n_allow  mean_prod   emissions    mean_cash  \
0         4.64     0.000000  331.000000  81.731699  510.050463   817.316993
1         4.76   107.455034  330.000000  55.283335  241.000000   773.423977
2         5.20   145.981494  329.262983  47.887665  352.000000   734.370430
3         6.04   192.518590  328.271360  56.996670  237.000000   755.345216
4         6.32   313.059586  327.271360  66.031394  303.000000   803.587517
..         ...          ...         ...        ...         ...          ...
195       9.16   744.230234  199.289719  83.022424  165.000000  1142.419211
196       9.16   647.565854  199.289719  77.390364  184.000000  1125.239526
197       9.16   626.604532  199.289719  83.711825  151.000000  1158.211821
198       9.16   487.750897  199.289719  71.981739  244.000000  1117.854182
199       9.16   414.248415  199.289719  76.754854  194.000000  1122.141676

     period
0         0
1         1
2         2
3         3
4         4
..      ...
195     195
196     196
197     197
198     198
199     199

[200 rows x 7 columns]), ((True, 25, 0.35, 0.5, 0.33, 0.005, 4),      mean_tech  total_lobby     n_allow   mean_prod   emissions    mean_cash  \
0         4.00     0.000000  538.000000   71.516558  828.552783   715.165576
1         4.00   209.425912  537.644571   60.568376  349.000000   649.851994
2         4.56   334.311550  536.028889   56.692514  480.000000   621.218924
3         5.40   560.644845  534.168167   70.534704  385.000000   678.862549
4         6.00   720.546887  532.168167   71.764305  446.000000   715.572265
..         ...          ...         ...         ...         ...          ...
195       9.08  1861.531505  329.742791   96.177779  388.000000  1040.770960
196       9.08  1976.989265  328.896992   99.183690  288.000000  1054.679520
197       9.08  1898.011361  327.896992  101.723973  337.000000  1118.033469
198       9.08  1916.310778  327.193144   99.989609  383.000000  1096.797369
199       9.08  1696.793920  326.787496   92.630206  373.000000  1041.471181

     period
0         0
1         1
2         2
3         3
4         4
..      ...
195     195
196     196
197     197
198     198
199     199

[200 rows x 7 columns]), ((True, 25, 0.35, 0.5, 0.33, 0.005, 5),      mean_tech  total_lobby     n_allow   mean_prod   emissions    mean_cash  \
0         3.84     0.000000  568.000000   76.304613  873.899372   763.046134
1         4.00   197.255823  567.302170   59.083931  379.000000   653.890912
2         4.60   248.890954  565.302170   52.567974  555.000000   615.360359
3         5.44   389.695123  563.302170   67.774124  436.000000   684.311698
4         5.84   554.918976  561.302170   76.665523  492.000000   761.733152
..         ...          ...         ...         ...         ...          ...
195       9.72  2330.759196  345.481970  106.712166  310.000000  1168.467132
196       9.72  2480.410194  345.063675  107.443432  303.000000  1169.745542
197       9.72  2331.718158  344.063675  113.080533  361.000000  1257.014676
198       9.72  2322.728552  343.063675  104.647835  356.000000  1193.551121
199       9.72  1966.346094  342.201738  104.317470  389.000000  1205.947554

     period
0         0
1         1
2         2
3         3
4         4
..      ...
195     195
196     196
197     197
198     198
199     199

[200 rows x 7 columns]), ((True, 25, 0.35, 0.5, 0.33, 0.005, 3),      mean_tech  total_lobby     n_allow   mean_prod  emissions    mean_cash  \
0         3.48     0.000000  621.000000   74.045962  956.12125   740.459619
1         3.56   231.837538  618.708593   64.351894  402.00000   709.869060
2         4.36   337.805864  616.700156   61.069133  463.00000   706.238088
3         5.24   576.408587  613.700156   72.362627  447.00000   733.611547
4         5.68   896.967890  613.288044   82.490996  482.00000   788.677380
..         ...          ...         ...         ...        ...          ...
195       9.76  3180.508413  366.545132  116.811226  513.00000  1243.272424
196       9.76  2789.981048  366.215639  117.685914  387.00000  1294.424306
197       9.76  3030.491296  365.845128  120.171034  413.00000  1282.786582
198       9.76  2925.625666  364.845128  117.796416  361.00000  1281.171453
199       9.76  2801.694479  364.243136  121.467707  341.00000  1334.764194

     period
0         0
1         1
2         2
3         3
4         4
..      ...
195     195
196     196
197     197
198     198
199     199

[200 rows x 7 columns]), ((True, 25, 0.35, 0.5, 0.33, 0.005, 2),      mean_tech  total_lobby     n_allow   mean_prod  emissions    mean_cash  \
0         4.24     0.000000  617.000000   73.065085  949.37095   730.650845
1         4.28   245.065249  615.066598   62.918387  365.00000   683.049536
2         4.84   421.977759  612.421099   58.191828  554.00000   647.064417
3         5.60   562.362175  609.757896   67.300924  409.00000   703.320668
4         6.08   839.375339  606.802916   76.514312  473.00000   744.955047
..         ...          ...         ...         ...        ...          ...
195       9.72  2792.006016  369.827025  118.958524  355.00000  1244.513442
196       9.72  3003.301923  369.007498  119.694834  355.00000  1255.922344
197       9.72  2813.248387  368.007498  117.765708  486.00000  1283.243445
198       9.72  3222.664138  367.285152  119.336868  425.00000  1242.883080
199       9.72  3288.002282  366.877109  117.614473  450.00000  1235.201607

     period
0         0
1         1
2         2
3         3
4         4
..      ...
195     195
196     196
197     197
198     198
199     199

[200 rows x 7 columns]), ((True, 25, 0.35, 0.5, 0.33, 0.005, 0),      mean_tech  total_lobby     n_allow   mean_prod    emissions    mean_cash  \
0         4.36     0.000000  744.000000   80.683659  1145.250847   806.836588
1         4.40   271.880511  741.063551   61.422197   447.000000   640.956243
2         4.84   539.421803  738.063551   72.533926   536.000000   696.355987
3         5.72   817.127014  735.666830   74.621651   620.000000   709.699695
4         6.36  1167.980341  732.666830   85.429071   683.000000   773.045246
..         ...          ...         ...         ...          ...          ...
195       9.96  3094.935085  417.487654  128.391864   472.000000  1332.191294
196       9.96  3005.679111  416.366177  129.160000   468.000000  1352.387794
197       9.96  2948.195856  415.983455  129.160000   343.000000  1369.179539
198       9.96  3052.752766  414.059976  128.671187   447.000000  1357.762510
199       9.96  3253.805576  412.059976  128.783833   334.000000  1337.589476

     period
0         0
1         1
2         2
3         3
4         4
..      ...
195     195
196     196
197     197
198     198
199     199

[200 rows x 7 columns]), ((True, 25, 0.35, 0.5, 0.33, 0.005, 8),      mean_tech  total_lobby     n_allow  mean_prod   emissions   mean_cash  \
0         4.68     0.000000  392.000000  62.883238  604.205307  628.832379
1         4.72   159.247088  391.000000  51.259210  276.000000  577.620854
2         5.16   305.072736  390.867054  54.140611  275.000000  592.719692
3         6.00   475.289465  390.213918  58.895548  363.000000  617.245417
4         6.48   601.431988  389.259172  62.236436  332.000000  640.330883
..         ...          ...         ...        ...         ...         ...
195       8.68   911.432690  249.998845  76.533469  293.000000  854.170467
196       8.68   957.756580  249.405127  80.445451  237.000000  890.540605
197       8.68   928.683082  248.405127  76.840354  227.000000  873.232920
198       8.68   785.410270  248.036253  74.820052  219.000000  878.584539
199       8.68   837.652889  247.911052  70.122782  252.000000  798.969295

     period
0         0
1         1
2         2
3         3
4         4
..      ...
195     195
196     196
197     197
198     198
199     199

[200 rows x 7 columns]), ((True, 25, 0.35, 0.5, 0.33, 0.005, 6),      mean_tech  total_lobby     n_allow  mean_prod   emissions    mean_cash  \
0         3.88     0.000000  410.000000  70.012120  631.185821   700.121200
1         3.88   102.608441  408.000000  44.972006  322.000000   611.911641
2         4.12   221.000487  407.362001  50.553247  380.000000   623.689553
3         4.80   312.791137  406.404434  58.654858  260.000000   689.330731

In [52]:
lst = []
for key, value in od.items():
    auction = [key[0] for i in range(len(value.mean_tech))]
    iteration = [key[6] for i in range(len(value))]
    value["Auction"] = auction
    value["Iteration"] = iteration
    lst.append(value)

In [53]:
df = pd.concat(lst)

In [54]:
df.to_csv("out_data/AuctionExperiment.csv")

Cap Size and Decrement Experiment

In [69]:
#Experiment 2 Variables 
fixed_params2 = {
  "N": 25,
  "am": True,
  "mSize":  .5,
  "lobby": .33,
}
variable_params = {
  "cap_size": [.1, .2, .3, .4, .5, .6, .7, .8, .9],
  "dec": np.arange(.001, .01, .001)
}

In [70]:
experiment2 = BatchRunnerMP(Environment,
    nr_processes= None,
    variable_parameters = variable_params2, 
    fixed_parameters = fixed_params2,
    iterations = 1,
    max_steps = 200)

BatchRunner MP will use 16 processors.

In [71]:
experiment2.run_all()

108it [00:59,  1.81it/s]

(None,
 None,
 OrderedDict([((0.1, 0.008, 25, True, 0.5, 0.33, 0),
                    mean_tech  total_lobby     n_allow  mean_prod   emissions    mean_cash  \
               0         3.88     0.000000  582.000000  68.901594  647.526629   689.015939
               1         3.92   325.468973  578.000000  58.170341  383.000000   629.295189
               2         4.32   562.970458  575.655568  60.695200  371.000000   637.667775
               3         5.28   627.137399  573.906907  66.814845  404.000000   704.448490
               4         5.88   928.552754  572.670780  77.522027  430.000000   753.960166
               ..         ...          ...         ...        ...         ...          ...
               195       9.12  1231.093771  233.306745  93.162018  294.000000  1145.674238
               196       9.12  1344.250626  232.306745  83.637604  207.000000  1060.823607
               197       9.12  1240.006201  231.306745  85.368584  199.000000  1065.852974
               198       9.12  1329.034489  230.306745  88.761259  208.000000  1084.133005
               199       9.12  1156.063220  229.934844  84.436302  276.000000  1093.138954

                    period
               0         0
               1         1
               2         2
               3         3
               4         4
               ..      ...
               195     195
               196     196
               197     197
               198     198
               199     199

               [200 rows x 7 columns]),
              ((0.1, 0.009000000000000001, 25, True, 0.5, 0.33, 0),
                    mean_tech  total_lobby     n_allow  mean_prod   emissions    mean_cash  \
               0         4.24     0.000000  721.000000  72.741845  801.804769   727.418451
               1         4.28   479.698071  715.000000  64.290578  475.000000   636.215211
               2         4.88   645.857093  711.933417  58.746441  630.000000   595.773182
               3         5.72   901.887880  709.774977  67.044583  396.000000   628.649508
               4         6.16  1488.157860  703.774977  83.467052  387.000000   715.937382
               ..         ...          ...         ...        ...         ...          ...
               195       9.32  1456.587636  254.090990  88.849295  333.000000  1106.195298
               196       9.32  1302.549014  252.090990  83.362941  259.000000  1077.990809
               197       9.32  1316.961031  250.090990  91.617968  299.000000  1135.765941
               198       9.32  1299.782998  248.633634  79.424331  446.000000  1034.068548
               199       9.32  1238.630196  246.633634  82.529105  252.000000  1041.133531

                    period
               0         0
               1         1
               2         2
               3         3
               4         4
               ..      ...
               195     195
               196     196
               197     197
               198     198
               199     199

               [200 rows x 7 columns]),
              ((0.15000000000000002, 0.006, 25, True, 0.5, 0.33, 0),
                    mean_tech  total_lobby     n_allow   mean_prod  emissions    mean_cash  \
               0         4.04     0.000000  716.000000   83.448527  843.36847   834.485270
               1         4.08   235.814285  713.608787   60.938582  592.00000   687.747852
               2         4.48   535.000015  711.140078   68.601168  537.00000   665.989798
               3         5.36   865.269245  707.140078   78.053552  438.00000   725.750346
               4         6.12  1186.375288  705.257335   91.416230  482.00000   841.554510
               ..         ...          ...         ...         ...        ...          ...
               195       9.60  3305.802850  372.074062  125.753267  375.00000  1313.096663
               196       9.60  3743.035763  370.074062  128.166696  388.00000  1311.311789
               197       9.60  3280.097765  368.074062  125.782157  383.00000  1362.118430
               198       9.60  3048.087262  367.128563  122.298530  487.00000  1358.239015
               199       9.60  2807.076177  365.983262  123.276529  540.00000  1361.425828

                    period
               0         0
               1         1
               2         2
               3         3
               4         4
               ..      ...
               195     195
               196     196
               197     197
               198     198
               199     199

               [200 rows x 7 columns]),
              ((0.15000000000000002, 0.002, 25, True, 0.5, 0.33, 0),
                    mean_tech  total_lobby     n_allow   mean_prod   emissions    mean_cash  \
               0         5.08     0.000000  667.000000   89.591941  785.400088   895.919408
               1         5.12   134.132748  666.162606   74.083772  456.000000   723.475053
               2         5.72   237.295892  665.333465   76.074794  441.000000   743.916865
               3         6.64   368.701071  664.410358   82.041957  454.000000   777.347624
               4         7.16   571.644335  663.767098   95.124555  505.000000   863.168053
               ..         ...          ...         ...         ...         ...          ...
               195      10.24  3965.459402  527.755386  126.840000  243.000000  1153.863246
               196      10.24  3926.012702  526.755386  126.840000  667.000000  1135.648498
               197      10.24  3747.712153  525.904467  126.840000  331.000000  1160.616324
               198      10.24  3491.301631  524.904467  126.840000  527.000000  1172.320511
               199      10.24  3895.197748  523.904467  126.840000  396.000000  1135.411679

                    period
               0         0
               1         1
               2         2
               3         3
               4         4
               ..      ...
               195     195
               196     196
               197     197
               198     198
               199     199

               [200 rows x 7 columns]),
              ((0.1, 0.007, 25, True, 0.5, 0.33, 0),
                    mean_tech  total_lobby     n_allow   mean_prod  emissions    mean_cash  \
               0         4.84     0.000000  830.000000   68.963530  923.33199   689.635297
               1         4.92   460.876783  825.296159   65.914443  400.00000   580.103890
               2         5.44   833.498314  820.296159   64.352933  522.00000   547.627936
               3         6.28  1054.325045  817.143748   68.291050  622.00000   580.498974
               4         6.60  1545.306672  815.604037   79.242325  502.00000   619.213196
               ..         ...          ...         ...         ...        ...          ...
               195       9.00  1969.052689  356.041542  100.150860  349.00000  1031.874449
               196       9.00  2253.686497  355.711204  100.238625  320.00000   991.098520
               197       9.00  2303.756265  353.711204  100.520000  473.00000   994.131627
               198       9.00  2328.715289  352.013941  100.520000  388.00000  1000.875012
               199       9.00  2528.809708  351.703483  100.359685  301.00000   976.742658

                    period
               0         0
               1         1
               2         2
               3         3
               4         4
               ..      ...
               195     195
               196     196
               197     197
               198     198
               199     199

               [200 rows x 7 columns]),
              ((0.1, 0.003, 25, True, 0.5, 0.33, 0),
                    mean_tech  total_lobby     n_allow   mean_prod   emissions    mean_cash  \
               0         5.08     0.000000  689.000000   85.449601  766.201819   854.496008
               1         5.16   177.602887  688.454993   72.520174  457.000000   715.321583
               2         5.64   281.332393  688.246993   74.707177  401.000000   765.522805
               3         6.44   370.352797  687.409559   76.811603  650.000000   770.688831
               4         6.92   620.269113  686.869324   84.636319  549.000000   759.894966
               ..         ...          ...         ...         ...         ...          ...
               195      10.12  3266.930608  547.321159  129.000000  475.000000  1171.228635
               196      10.12  3172.490944  546.355988  129.000000  531.000000  1177.803244
               197      10.12  3352.370083  545.467013  129.000000  411.000000  1167.909196
               198      10.12  3906.212899  544.467013  129.000000  369.000000  1122.228694
               199      10.12  3654.400444  543.789958  129.000000  442.000000  1162.472930

                    period
               0         0
               1         1
               2         2
               3         3
               4         4
               ..      ...
               195     195
               196     196
               197     197
               198     198
               199     199

               [200 rows x 7 columns]),
              ((0.15000000000000002, 0.005, 25, True, 0.5, 0.33, 0),
                    mean_tech  total_lobby     n_allow   mean_prod   emissions    mean_cash  \
               0         3.76     0.000000  717.000000   68.589776  844.230566   685.897765
               1         3.80   252.096820  716.549093   60.163819  436.000000   616.208150
               2         4.24   501.177747  714.808982   61.543277  535.000000   599.983409
               3         5.12   641.815304  712.734211   63.808499  619.000000   620.984397
               4         5.76   871.285524  709.884698   72.356593  623.000000   655.074183
               ..         ...          ...         ...         ...         ...          ...
               195       9.32  3185.921254  399.320539  110.880000  387.000000  1100.459216
               196       9.32  3319.990864  398.922032  110.880000  353.000000  1093.501365
               197       9.32  3166.400535  398.181556  110.880000  404.000000  1115.038377
               198       9.32  3231.460053  397.181556  110.880000  463.000000  1111.084304
               199       9.32  3084.864088  396.304107  110.880000  347.000000  1112.100078

                    period
               0         0
               1         1
               2         2
               3         3
               4         4
               ..      ...
               195     195
               196     196
               197     197
               198     198
               199     199

               [200 rows x 7 columns]),
              ((0.1, 0.006, 25, True, 0.5, 0.33, 0),
                    mean_tech  total_lobby     n_allow   mean_prod   emissions    mean_cash  \
               0         3.36     0.000000  789.000000   75.345990  876.765075   753.459896
               1         3.40   346.935228  785.000000   68.315655  548.000000   688.105332
               2         4.04   602.512649  783.622535   73.561037  442.000000   722.730270
               3         5.00   819.311203  782.659552   73.175216  572.000000   710.034256
               4         5.64   963.080690  781.165099   79.436566  816.000000   740.710227
               ..         ...          ...         ...         ...         ...          ...
               195       9.52  3017.959889  404.252096  119.944931  707.000000  1207.250920
               196       9.52  3100.904215  402.915273  121.353857  468.000000  1232.339735
               197       9.52  3003.064289  402.064137  121.262411  592.000000  1264.035642
               198       9.52  2850.130870  400.544364  119.029103  574.000000  1256.457030
               199       9.52  3484.886586  398.544364  119.332406  560.000000  1188.657945

                    period
               0         0
               1         1
               2         2
               3         3
               4         4
               ..      ...
               195     195
               196     196
               197     197
               198     198
               199     199

               [200 rows x 7 columns]),
              ((0.15000000000000002, 0.001, 25, True, 0.5, 0.33, 0),
                    mean_tech  total_lobby  n_allow   mean_prod   emissions    mean_cash  \
               0         3.72     0.000000    597.0   73.327621  702.828071   733.276214
               1         3.76    41.744880    597.0   59.222399  369.000000   649.170333
               2         4.20    86.179380    597.0   63.658245  460.000000   636.597708
               3         5.00   133.281961    597.0   72.170216  471.000000   713.107636
               4         5.76   178.977931    597.0   80.141224  386.000000   788.960198
               ..         ...          ...      ...         ...         ...          ...
               195       9.56  2749.168173    597.0  115.880000  473.000000   992.987625
               196       9.56  2643.771960    597.0  115.880000  405.000000   999.404683
               197       9.56  2541.076042    597.0  115.880000  468.000000  1000.822856
               198       9.56  2814.109504    597.0  115.880000  489.000000   967.980984
               199       9.56  2750.949690    597.0  115.880000  273.000000   997.666970

                    period
               0         0
               1         1
               2         2
               3         3
               4         4
               ..      ...
               195     195
               196     196
               197     197
               198     198
               199     199

               [200 rows x 7 columns]),
              ((0.15000000000000002, 0.007, 25, True, 0.5, 0.33, 0),
                    mean_tech  total_lobby     n_allow   mean_prod    emissions    mean_cash  \
               0         3.80     0.000000  900.000000   75.795244  1059.438701   757.952440
               1         3.80   441.397350  895.917432   65.729249   525.000000   638.383718
               2         4.40   757.757049  889.917432   69.477877   584.000000   647.015596
               3         5.32  1104.656703  887.234725   79.380563   430.000000   705.453329
               4         5.88  1452.072850  883.664963   87.798454   498.000000   773.950838
               ..         ...          ...         ...         ...          ...          ...
               195       9.56  3338.987533  389.052350  122.200000   804.000000  1281.042495
               196       9.56  3818.091290  387.296795  122.200000   359.000000  1237.489700
               197       9.56  4041.274788  385.296795  122.200000   507.000000  1231.133780
               198       9.56  3240.747788  383.296795  122.200000   359.000000  1310.351310
               199       9.56  3189.003990  381.296795  122.200000   337.000000  1310.603778

                    period
               0         0
               1         1
               2         2
               3         3
               4         4
               ..      ...
               195     195
               196     196
               197     197
               198     198
               199     199

               [200 rows x 7 columns]),
              ((0.1, 0.004, 25, True, 0.5, 0.33, 0),
                    mean_tech  total_lobby     n_allow   mean_prod   emissions    mean_cash  \
               0         4.60     0.000000  798.000000   91.827384  886.769765   918.273839
               1         4.68   257.200824  796.370084   78.189157  530.000000   796.410138
               2         5.12   526.933950  793.370084   81.614917  543.000000   774.353497
               3         6.08   763.350775  790.370084   84.288562  620.000000   799.334324
               4         6.64  1076.178874  789.358721   93.217185  681.000000   842.923256
               ..         ...          ...         ...         ...         ...          ...
               195      10.00  3845.564054  503.099324  136.040000  671.000000  1305.003348
               196      10.00  4114.271681  501.099324  136.040000  465.000000  1291.040453
               197      10.00  4187.464745  499.099324  136.040000  317.000000  1295.280425
               198      10.00  3927.413277  498.099324  136.040000  679.000000  1335.122877
               199      10.00  3611.819620  497.278695  136.040000  516.000000  1346.831658

                    period
               0         0
               1         1
               2         2
               3         3
               4         4
               ..      ...
               195     195
               196     196
               197     197
               198     198
               199     199

               [200 rows x 7 columns]),
              ((0.1, 0.002, 25, True, 0.5, 0.33, 0),
                    mean_tech  total_lobby     n_allow   mean_prod   emissions    mean_cash  \
               0         3.04     0.000000  739.000000   64.950370  822.096322   649.503697
               1         3.04   104.087270  738.268273   51.965897  513.000000   551.064834
               2         3.60   192.702140  737.740700   54.445617  553.000000   551.660873
               3         4.40   241.447120  737.622294   64.373367  547.000000   651.453034
               4         5.08   347.771269  737.192226   73.604516  531.000000   699.567412
               ..         ...          ...         ...         ...         ...          ...
               195       9.40  3302.029078  599.328058  119.065789  463.000000  1001.365413
               196       9.40  2783.240230  598.626460  119.149120  294.000000  1059.960642
               197       9.40  2903.925866  597.626460  119.179641  294.000000  1047.555047
               198       9.40  2882.161258  596.709738  119.111929  359.000000  1035.975448
               199       9.40  3073.104305  596.197215  119.109180  457.000000  1012.132465

                    period
               0         0
               1         1
               2         2
               3         3
               4         4
               ..      ...
               195     195
               196     196
               197     197
               198     198
               199     199

               [200 rows x 7 columns]),
              ((0.15000000000000002, 0.003, 25, True, 0.5, 0.33, 0),
                    mean_tech  total_lobby     n_allow   mean_prod    emissions    mean_cash  \
               0         3.92     0.000000  884.000000   80.876312  1040.068101   808.763124
               1         3.92   214.975268  882.000000   69.039523   578.000000   669.499795
               2         4.36   417.282850  880.000000   73.220967   606.000000   699.767985
               3         5.36   574.603018  878.000000   77.359526   673.000000   710.480371
               4         6.00   902.891759  877.242492   89.293944   554.000000   769.774899
               ..         ...          ...         ...         ...          ...          ...
               195       9.96  3879.835652  631.969093  132.040000   346.000000  1140.689539
               196       9.96  4164.739151  631.019044  132.040000   524.000000  1131.941192
               197       9.96  4337.762369  630.478285  132.040000   412.000000  1120.260929
               198       9.96  4762.449719  629.478285  132.040000   552.000000  1094.944367
               199       9.96  4145.615185  628.478285  132.040000   427.000000  1158.709989

                    period
               0         0
               1         1
               2         2
               3         3
               4         4
               ..      ...
               195     195
               196     196
               197     197
               198     198
               199     199

               [200 rows x 7 columns]),
              ((0.1, 0.005, 25, True, 0.5, 0.33, 0),

In [72]:
dic = experiment2.get_collector_model()

In [73]:
len(list(dic.values()))

108

In [60]:
data = []
for key, value in dic.items():
    initial_cap = [key[0] for i in range(len(value))]
    decrement = [key[1] for i in range(len(value))]
    iteration = [key[6] for i in range(len(value))]
    value["init_cap"] = initial_cap
    value["decrement"] = decrement
    value["Iteration"] = iteration
    data.append(value)

In [61]:
len(data)

108

In [62]:
df2 = pd.concat(data)

In [63]:
df2.to_csv("out_data/Cap_and_Dec_Experiment.csv")